/**
 * 패스프레이즈 생성용 영문 일반 단어 목록.
 * 발음·기억이 쉬운 짧은 단어로 구성(고유명사·민감어 제외).
 */
export const PASSPHRASE_WORDS: ReadonlyArray<string> = [
  'able', 'acid', 'acre', 'aged', 'also', 'amber', 'angle', 'apple', 'apron', 'area',
  'arrow', 'aspen', 'atlas', 'autumn', 'axis', 'bacon', 'badge', 'baker', 'banjo', 'basil',
  'basin', 'beach', 'beam', 'bean', 'bear', 'beef', 'berry', 'birch', 'bird', 'black',
  'blade', 'blaze', 'blend', 'block', 'bloom', 'blue', 'board', 'boat', 'bolt', 'bone',
  'bonus', 'book', 'boot', 'brave', 'bread', 'brick', 'bridge', 'brief', 'broom', 'brown',
  'brush', 'bunny', 'cabin', 'cable', 'cake', 'camel', 'candy', 'cane', 'canoe', 'canvas',
  'cargo', 'carrot', 'castle', 'cedar', 'chair', 'chalk', 'charm', 'cheese', 'cherry', 'chess',
  'chime', 'cider', 'cliff', 'cloud', 'clover', 'coal', 'coast', 'cocoa', 'comet', 'coral',
  'cotton', 'cove', 'crane', 'cream', 'creek', 'crisp', 'crow', 'crystal', 'cube', 'daisy',
  'dawn', 'deer', 'delta', 'denim', 'dew', 'diner', 'dock', 'dome', 'dove', 'dragon',
  'dream', 'drift', 'drum', 'dune', 'dusk', 'eagle', 'earth', 'east', 'echo', 'ember',
  'fable', 'falcon', 'fancy', 'farm', 'fawn', 'fern', 'ferry', 'field', 'finch', 'fjord',
  'flame', 'flax', 'flint', 'float', 'flora', 'flour', 'flute', 'foam', 'fog', 'forest',
  'fox', 'frost', 'fruit', 'galaxy', 'garden', 'gate', 'gem', 'ginger', 'glade', 'glass',
  'glow', 'goat', 'gold', 'goose', 'grain', 'grape', 'grass', 'green', 'grove', 'guava',
  'gulf', 'hammer', 'harbor', 'hawk', 'hazel', 'heron', 'hill', 'honey', 'horse', 'house',
  'ice', 'iris', 'island', 'ivory', 'ivy', 'jade', 'jam', 'jazz', 'jelly', 'jewel',
  'jolly', 'jungle', 'kayak', 'kelp', 'kettle', 'key', 'kite', 'koala', 'lake', 'lamb',
  'lamp', 'lantern', 'lark', 'lava', 'leaf', 'ledge', 'lemon', 'lily', 'lime', 'linen',
  'lion', 'lizard', 'llama', 'lock', 'lotus', 'lumber', 'lunar', 'lynx', 'maple', 'marble',
  'marsh', 'meadow', 'melon', 'mesa', 'mint', 'mist', 'moon', 'moss', 'moth', 'mouse',
  'mug', 'nectar', 'nest', 'noble', 'north', 'nut', 'oak', 'oasis', 'ocean', 'olive',
  'onyx', 'opal', 'orange', 'orbit', 'otter', 'owl', 'palm', 'panda', 'paper', 'pearl',
  'pebble', 'pepper', 'petal', 'piano', 'pier', 'pine', 'pixel', 'plum', 'pond', 'poppy',
  'prairie', 'puma', 'quail', 'quartz', 'quill', 'quilt', 'rabbit', 'radar', 'raft', 'rain',
  'raven', 'reed', 'reef', 'ridge', 'river', 'robin', 'rocket', 'rose', 'ruby', 'rust',
  'saddle', 'sage', 'sail', 'salt', 'sand', 'sapphire', 'scarf', 'sea', 'seed', 'shadow',
  'shark', 'sheep', 'shell', 'shore', 'silk', 'silver', 'sky', 'sled', 'sloth', 'smoke',
  'snail', 'snow', 'solar', 'south', 'spark', 'spider', 'spruce', 'square', 'squid', 'stag',
  'star', 'steam', 'stone', 'storm', 'stream', 'sugar', 'summit', 'sun', 'swan', 'swift',
  'table', 'tea', 'teak', 'thorn', 'tide', 'tiger', 'toast', 'tomato', 'topaz', 'torch',
  'tower', 'trail', 'tulip', 'tundra', 'turtle', 'valley', 'vanilla', 'velvet', 'vine', 'violet',
  'walnut', 'wave', 'west', 'whale', 'wheat', 'willow', 'wind', 'wolf', 'wood', 'wren',
  'yarn', 'yeast', 'zebra', 'zen', 'zephyr', 'zinc',
];
