/**
 * 도구 레지스트리. 허브 페이지가 이 목록으로 카드 그리드를 렌더.
 *
 * 새 도구 추가 시:
 *   1) 페이지 경로 (href) 에 맞게 app/tools/{slug}/page.tsx 생성
 *   2) 이 파일에 ToolMeta 를 push 하고 status: 'ready' 지정
 */

import type { LucideIcon } from 'lucide-react';
import {
  Archive,
  Barcode,
  BookOpen,
  Braces,
  Clapperboard,
  Clock,
  Crop,
  Diff,
  Droplet,
  Eraser,
  FastForward,
  FileImage,
  FileLock,
  FileMinus,
  FilePlus,
  FileSearch,
  FileText,
  FileVideo,
  Film,
  Fingerprint,
  FileCode,
  Hash as HashIcon,
  Hexagon,
  Images,
  Info,
  Key,
  KeyRound,
  Layers,
  Link2,
  Maximize2,
  Merge,
  Music,
  Palette,
  PenTool,
  QrCode,
  Regex,
  RotateCw,
  Ruler,
  ScanText,
  Scissors,
  ShieldOff,
  Shuffle,
  SplitSquareHorizontal,
  Stamp,
  Table,
  Type,
  Volume2,
  Wand2,
} from 'lucide-react';

export type ToolCategory =
  | 'image'
  | 'pdf'
  | 'security'
  | 'ai'
  | 'video'
  | 'gif'
  | 'audio'
  | 'util'
  | 'docs'
  | 'text'
  | 'dev';
export type ToolStatus = 'ready' | 'planned';

export interface ToolMeta {
  id: string;
  title: string;
  description: string;
  href: string;
  category: ToolCategory;
  icon: LucideIcon;
  status: ToolStatus;
  /** 구현 Phase 로 정렬. 1 = 우선순위 최상위. */
  phase: 1 | 2 | 3 | 4 | 5 | 6 | 7;
  /** 검색에서 매칭될 추가 키워드 (한/영) */
  keywords?: string[];
}

export const CATEGORY_LABELS: Record<ToolCategory | 'all', string> = {
  all: '전체',
  image: '이미지',
  pdf: 'PDF',
  video: '비디오',
  gif: 'GIF',
  audio: '오디오',
  docs: '문서 변환',
  text: '텍스트',
  dev: '개발자',
  util: '유틸',
  security: '보안',
  ai: 'AI',
};

export const TOOLS: ToolMeta[] = [
  // ---- Ready ----
  {
    id: 'compress',
    title: '파일 용량 줄이기',
    description: '이미지와 PDF 를 브라우저에서 압축합니다.',
    href: '/tools/compress',
    category: 'pdf',
    icon: Wand2,
    status: 'ready',
    phase: 1,
    keywords: ['압축', '용량', 'compress', 'shrink', 'reduce'],
  },

  // ---- Phase 1: 고빈도 PDF ----
  {
    id: 'pdf-merge',
    title: 'PDF 합치기',
    description: '여러 PDF 파일을 하나로 병합합니다.',
    href: '/tools/pdf/merge',
    category: 'pdf',
    icon: Merge,
    status: 'ready',
    phase: 1,
    keywords: ['merge', 'combine', '병합'],
  },
  {
    id: 'pdf-split',
    title: 'PDF 분할',
    description: '페이지 범위로 PDF 를 나눕니다.',
    href: '/tools/pdf/split',
    category: 'pdf',
    icon: SplitSquareHorizontal,
    status: 'ready',
    phase: 1,
    keywords: ['split', 'divide', '분할', '나누기'],
  },
  {
    id: 'pdf-rotate',
    title: 'PDF 회전',
    description: '선택한 페이지를 90/180/270도 회전합니다.',
    href: '/tools/pdf/rotate',
    category: 'pdf',
    icon: RotateCw,
    status: 'ready',
    phase: 1,
    keywords: ['rotate', '회전'],
  },
  {
    id: 'pdf-organize',
    title: 'PDF 페이지 정리',
    description: '페이지 재정렬·삭제·복제를 썸네일로 처리합니다.',
    href: '/tools/pdf/organize',
    category: 'pdf',
    icon: Shuffle,
    status: 'ready',
    phase: 1,
    keywords: ['organize', 'reorder', 'delete', '정리', '순서'],
  },
  {
    id: 'pdf-to-jpg',
    title: 'PDF → JPG',
    description: '각 페이지를 JPG 이미지로 추출합니다.',
    href: '/tools/pdf/to-jpg',
    category: 'pdf',
    icon: FileImage,
    status: 'ready',
    phase: 1,
    keywords: ['extract', 'image', '이미지 추출', '변환'],
  },
  {
    id: 'pdf-from-jpg',
    title: 'JPG → PDF',
    description: '여러 이미지를 하나의 PDF 로 묶습니다.',
    href: '/tools/pdf/from-jpg',
    category: 'pdf',
    icon: FileText,
    status: 'ready',
    phase: 1,
    keywords: ['convert', '변환', 'combine'],
  },
  {
    id: 'pdf-page-numbers',
    title: 'PDF 페이지 번호',
    description: '페이지 번호를 일괄 삽입합니다.',
    href: '/tools/pdf/page-numbers',
    category: 'pdf',
    icon: Layers,
    status: 'ready',
    phase: 1,
    keywords: ['number', 'paginate', '페이지번호'],
  },
  {
    id: 'pdf-watermark',
    title: 'PDF 워터마크',
    description: '텍스트/이미지 워터마크를 추가합니다.',
    href: '/tools/pdf/watermark',
    category: 'pdf',
    icon: Stamp,
    status: 'ready',
    phase: 1,
    keywords: ['watermark', '워터마크'],
  },
  {
    id: 'pdf-crop',
    title: 'PDF 여백 자르기',
    description: '페이지 박스를 잘라 여백을 제거합니다.',
    href: '/tools/pdf/crop',
    category: 'pdf',
    icon: Crop,
    status: 'ready',
    phase: 1,
    keywords: ['crop', 'trim', '여백'],
  },

  // ---- Phase 2: 이미지 ----
  {
    id: 'image-resize',
    title: '이미지 리사이즈',
    description: '픽셀/비율/목표 용량으로 크기를 조정합니다.',
    href: '/tools/image/resize',
    category: 'image',
    icon: Maximize2,
    status: 'ready',
    phase: 2,
    keywords: ['resize', '크기', '조정'],
  },
  {
    id: 'image-crop',
    title: '이미지 자르기',
    description: '드래그로 영역 지정, 비율 프리셋 지원.',
    href: '/tools/image/crop',
    category: 'image',
    icon: Scissors,
    status: 'ready',
    phase: 2,
    keywords: ['crop', '자르기'],
  },
  {
    id: 'image-rotate',
    title: '이미지 회전/반전',
    description: '90/180/270도 회전 및 좌우·상하 반전.',
    href: '/tools/image/rotate',
    category: 'image',
    icon: RotateCw,
    status: 'ready',
    phase: 2,
    keywords: ['rotate', 'flip', '회전', '반전'],
  },
  {
    id: 'image-convert',
    title: '이미지 포맷 변환',
    description: 'JPG/PNG/WebP/AVIF 간 변환. 다중 파일 지원.',
    href: '/tools/image/convert',
    category: 'image',
    icon: FileImage,
    status: 'ready',
    phase: 2,
    keywords: ['convert', 'format', '변환', 'webp', 'avif'],
  },
  {
    id: 'image-watermark',
    title: '이미지 워터마크',
    description: '텍스트/로고 워터마크 합성.',
    href: '/tools/image/watermark',
    category: 'image',
    icon: Stamp,
    status: 'ready',
    phase: 2,
    keywords: ['watermark', '워터마크'],
  },
  {
    id: 'images-to-pdf',
    title: '여러 이미지 → PDF',
    description: '이미지를 순서대로 묶어 PDF 로 만듭니다.',
    href: '/tools/pdf/from-jpg',
    category: 'image',
    icon: Images,
    status: 'ready',
    phase: 2,
    keywords: ['convert', 'combine', 'PDF로'],
  },
  {
    id: 'image-batch-compress',
    title: '이미지 일괄 압축',
    description: '여러 장을 한 번에 압축하여 ZIP 으로 저장.',
    href: '/tools/image/batch-compress',
    category: 'image',
    icon: Archive,
    status: 'ready',
    phase: 2,
    keywords: ['batch', 'bulk', '일괄', 'zip'],
  },

  // ---- Phase 3: 보안/편집 ----
  {
    id: 'pdf-unlock',
    title: 'PDF 잠금 해제',
    description: '편집/인쇄 제한 제거 또는 열람 암호 해제 (래스터화).',
    href: '/tools/pdf/unlock',
    category: 'security',
    icon: ShieldOff,
    status: 'ready',
    phase: 3,
    keywords: ['unlock', 'decrypt', '잠금', '암호해제'],
  },
  {
    id: 'pdf-protect',
    title: 'PDF 암호 설정',
    description: '열람·권한 암호와 세부 권한(인쇄·편집·복사 등) 설정.',
    href: '/tools/pdf/protect',
    category: 'security',
    icon: FileLock,
    status: 'ready',
    phase: 3,
    keywords: ['protect', 'encrypt', 'password', '암호설정'],
  },
  {
    id: 'pdf-sign',
    title: 'PDF 서명',
    description: '마우스/터치로 직접 서명하여 PDF 에 삽입합니다.',
    href: '/tools/pdf/sign',
    category: 'security',
    icon: PenTool,
    status: 'ready',
    phase: 3,
    keywords: ['sign', 'signature', '서명'],
  },
  {
    id: 'pdf-repair',
    title: 'PDF 복구',
    description: '2단계 복구: 구조 복원 + 래스터 재조립 폴백.',
    href: '/tools/pdf/repair',
    category: 'security',
    icon: FilePlus,
    status: 'ready',
    phase: 3,
    keywords: ['repair', 'fix', '복구'],
  },

  // ---- Phase 4: AI ----
  {
    id: 'ocr',
    title: 'OCR (이미지/PDF → 텍스트)',
    description: '한국어 포함 이미지·PDF 의 문자를 인식합니다. Tesseract 기반.',
    href: '/tools/ocr',
    category: 'ai',
    icon: ScanText,
    status: 'ready',
    phase: 4,
    keywords: ['ocr', 'text', '문자', '추출', 'tesseract'],
  },
  {
    id: 'remove-background',
    title: 'AI 배경 제거',
    description: '인물·상품 배경을 자동 분리. 투명 배경 PNG 출력.',
    href: '/tools/image/remove-background',
    category: 'ai',
    icon: Eraser,
    status: 'ready',
    phase: 4,
    keywords: ['background', 'bg', '배경', '누끼'],
  },
  {
    id: 'blur-face',
    title: '얼굴 블러',
    description: 'AI 로 얼굴 자동 감지 + 블러/모자이크. 수동 박스 추가 가능.',
    href: '/tools/image/blur-face',
    category: 'ai',
    icon: FileSearch,
    status: 'ready',
    phase: 4,
    keywords: ['face', 'blur', 'privacy', '모자이크', 'mosaic'],
  },
  {
    id: 'image-upscale',
    title: 'AI 이미지 업스케일',
    description: 'ESRGAN 초해상도로 2x/3x/4x 확대. 1MP 이하 권장.',
    href: '/tools/image/upscale',
    category: 'ai',
    icon: FileMinus,
    status: 'ready',
    phase: 4,
    keywords: ['upscale', 'enlarge', '확대', '업스케일', 'esrgan', 'sr'],
  },

  // ---- Phase 5: 비디오 & GIF (FFmpeg.wasm) ----
  {
    id: 'video-to-gif',
    title: '비디오 → GIF',
    description: '비디오의 구간을 GIF 애니메이션으로 변환합니다.',
    href: '/tools/video/to-gif',
    category: 'video',
    icon: Clapperboard,
    status: 'ready',
    phase: 5,
    keywords: ['gif', 'animation', 'ffmpeg', 'video', 'mp4'],
  },
  {
    id: 'video-convert',
    title: '비디오 포맷 변환',
    description: 'MP4 / WebM / MOV / AVI / MKV 상호 변환.',
    href: '/tools/video/convert',
    category: 'video',
    icon: FileVideo,
    status: 'ready',
    phase: 5,
    keywords: ['convert', 'format', 'mp4', 'webm', 'avi'],
  },
  {
    id: 'video-trim',
    title: '비디오 자르기',
    description: '구간 지정으로 비디오를 잘라냅니다.',
    href: '/tools/video/trim',
    category: 'video',
    icon: Scissors,
    status: 'ready',
    phase: 5,
    keywords: ['trim', 'cut', '자르기'],
  },
  {
    id: 'video-compress',
    title: '비디오 압축',
    description: '해상도·비트레이트 조정으로 용량을 줄입니다.',
    href: '/tools/video/compress',
    category: 'video',
    icon: Archive,
    status: 'ready',
    phase: 5,
    keywords: ['compress', 'shrink', '압축', '용량'],
  },
  {
    id: 'video-extract-frames',
    title: '비디오 → 프레임 추출',
    description: '각 프레임을 이미지로 추출합니다.',
    href: '/tools/video/extract-frames',
    category: 'video',
    icon: Film,
    status: 'ready',
    phase: 5,
    keywords: ['frames', 'extract', '프레임', '스틸'],
  },

  {
    id: 'gif-maker',
    title: 'GIF 만들기',
    description: '여러 이미지를 순서대로 애니메이션 GIF 로 묶습니다.',
    href: '/tools/gif/maker',
    category: 'gif',
    icon: Images,
    status: 'ready',
    phase: 5,
    keywords: ['gif', 'animate', 'maker', '만들기'],
  },
  {
    id: 'gif-resize',
    title: 'GIF 리사이즈',
    description: 'GIF 크기를 조정합니다.',
    href: '/tools/gif/resize',
    category: 'gif',
    icon: Maximize2,
    status: 'ready',
    phase: 5,
    keywords: ['resize', '크기'],
  },
  {
    id: 'gif-optimize',
    title: 'GIF 최적화',
    description: '팔레트·프레임 드롭으로 용량을 줄입니다.',
    href: '/tools/gif/optimize',
    category: 'gif',
    icon: Archive,
    status: 'ready',
    phase: 5,
    keywords: ['optimize', 'compress', '최적화', '용량'],
  },
  {
    id: 'gif-crop',
    title: 'GIF 영역 자르기',
    description: 'GIF 의 특정 영역만 잘라냅니다.',
    href: '/tools/gif/crop',
    category: 'gif',
    icon: Crop,
    status: 'ready',
    phase: 5,
    keywords: ['crop', '자르기'],
  },
  {
    id: 'gif-trim',
    title: 'GIF 구간 자르기',
    description: '시작·끝 시간을 지정하여 GIF 를 자릅니다.',
    href: '/tools/gif/trim',
    category: 'gif',
    icon: Scissors,
    status: 'ready',
    phase: 5,
    keywords: ['trim', 'cut', '구간'],
  },
  {
    id: 'gif-effects',
    title: 'GIF 효과',
    description: '역재생 · 배속 · 핑퐁 반복 효과를 적용합니다.',
    href: '/tools/gif/effects',
    category: 'gif',
    icon: FastForward,
    status: 'ready',
    phase: 5,
    keywords: ['reverse', 'speed', '역재생', '배속', 'pingpong'],
  },
  {
    id: 'gif-text',
    title: 'GIF 텍스트 삽입',
    description: 'GIF 전체에 표시될 텍스트·자막을 추가합니다.',
    href: '/tools/gif/text',
    category: 'gif',
    icon: Type,
    status: 'ready',
    phase: 5,
    keywords: ['text', 'caption', '자막'],
  },

  // ---- Phase 6: 오디오 & 유틸리티 ----
  {
    id: 'video-to-audio',
    title: '비디오 → MP3 (오디오 추출)',
    description: '비디오 파일에서 오디오 트랙을 추출하여 MP3/WAV 로 저장.',
    href: '/tools/audio/from-video',
    category: 'audio',
    icon: Music,
    status: 'ready',
    phase: 6,
    keywords: ['audio', 'extract', 'mp3', '오디오추출', '음원'],
  },
  {
    id: 'audio-convert',
    title: '오디오 포맷 변환',
    description: 'MP3 / WAV / OGG / AAC / M4A / FLAC 상호 변환.',
    href: '/tools/audio/convert',
    category: 'audio',
    icon: Volume2,
    status: 'ready',
    phase: 6,
    keywords: ['convert', 'mp3', 'wav', 'flac', '변환'],
  },
  {
    id: 'audio-trim',
    title: '오디오 자르기',
    description: '구간 지정으로 오디오를 잘라냅니다.',
    href: '/tools/audio/trim',
    category: 'audio',
    icon: Scissors,
    status: 'ready',
    phase: 6,
    keywords: ['trim', 'cut', '자르기'],
  },
  {
    id: 'audio-compress',
    title: '오디오 압축',
    description: '비트레이트를 낮춰 오디오 용량을 줄입니다.',
    href: '/tools/audio/compress',
    category: 'audio',
    icon: Archive,
    status: 'ready',
    phase: 6,
    keywords: ['compress', 'bitrate', '압축', '용량'],
  },

  {
    id: 'qr-code',
    title: 'QR 코드 생성/읽기',
    description: '텍스트·URL → QR 생성, 이미지 → QR 해독.',
    href: '/tools/util/qr',
    category: 'util',
    icon: QrCode,
    status: 'ready',
    phase: 6,
    keywords: ['qr', 'qrcode', '큐알'],
  },
  {
    id: 'barcode',
    title: '바코드 생성',
    description: 'Code128 / EAN / UPC 바코드를 생성합니다.',
    href: '/tools/util/barcode',
    category: 'util',
    icon: Barcode,
    status: 'ready',
    phase: 6,
    keywords: ['barcode', '바코드'],
  },
  {
    id: 'color-palette',
    title: '이미지 색상 팔레트',
    description: '이미지에서 주요 색상을 추출합니다.',
    href: '/tools/util/palette',
    category: 'util',
    icon: Palette,
    status: 'ready',
    phase: 6,
    keywords: ['color', 'palette', '색상', '팔레트'],
  },
  {
    id: 'file-hash',
    title: '파일 해시',
    description: 'SHA-1/256/512 · MD5 해시를 계산합니다.',
    href: '/tools/util/hash',
    category: 'util',
    icon: Fingerprint,
    status: 'ready',
    phase: 6,
    keywords: ['hash', 'sha', 'md5', '해시', '체크섬'],
  },
  {
    id: 'json-format',
    title: 'JSON 포맷터',
    description: 'JSON 포맷팅·압축·검증·트리 뷰.',
    href: '/tools/util/json',
    category: 'util',
    icon: Braces,
    status: 'ready',
    phase: 6,
    keywords: ['json', 'format', 'validate', '포맷팅'],
  },
  {
    id: 'base64',
    title: 'Base64 인코딩',
    description: '텍스트·파일을 Base64 로 변환 (양방향).',
    href: '/tools/util/base64',
    category: 'util',
    icon: FileCode,
    status: 'ready',
    phase: 6,
    keywords: ['base64', 'encode', 'decode'],
  },

  // ---- Phase 7: 문서 변환 / 텍스트 / 개발자 도구 ----
  {
    id: 'md-html',
    title: 'Markdown ↔ HTML',
    description: 'Markdown 과 HTML 상호 변환, 미리보기 포함.',
    href: '/tools/docs/md-html',
    category: 'docs',
    icon: FileText,
    status: 'ready',
    phase: 7,
    keywords: ['markdown', 'md', 'html', 'convert'],
  },
  {
    id: 'csv-json',
    title: 'CSV ↔ JSON',
    description: '스프레드시트 데이터를 JSON 으로 변환하거나 반대로.',
    href: '/tools/docs/csv-json',
    category: 'docs',
    icon: Table,
    status: 'ready',
    phase: 7,
    keywords: ['csv', 'json', 'tsv', '스프레드시트'],
  },
  {
    id: 'yaml-json',
    title: 'YAML ↔ JSON',
    description: 'YAML 과 JSON 상호 변환.',
    href: '/tools/docs/yaml-json',
    category: 'docs',
    icon: FileCode,
    status: 'ready',
    phase: 7,
    keywords: ['yaml', 'json', 'convert'],
  },
  {
    id: 'epub-to-pdf',
    title: 'EPUB → PDF',
    description: 'EPUB 전자책을 PDF 로 변환합니다. 50 MB 이하 권장.',
    href: '/tools/docs/epub-to-pdf',
    category: 'docs',
    icon: BookOpen,
    status: 'ready',
    phase: 7,
    keywords: ['epub', 'pdf', '전자책', 'ebook', 'convert', '변환', '책'],
  },

  {
    id: 'regex-tester',
    title: '정규식 테스터',
    description: '정규식을 실시간으로 테스트하고 매칭 결과를 확인.',
    href: '/tools/text/regex',
    category: 'text',
    icon: Regex,
    status: 'ready',
    phase: 7,
    keywords: ['regex', 'regexp', '정규식', 'pattern'],
  },
  {
    id: 'text-diff',
    title: '텍스트 비교 (Diff)',
    description: '두 텍스트의 차이를 줄 단위로 비교합니다.',
    href: '/tools/text/diff',
    category: 'text',
    icon: Diff,
    status: 'ready',
    phase: 7,
    keywords: ['diff', 'compare', '비교'],
  },
  {
    id: 'text-count',
    title: '단어·문자 카운트',
    description: '단어/문자/줄/바이트 수를 실시간 집계합니다.',
    href: '/tools/text/count',
    category: 'text',
    icon: HashIcon,
    status: 'ready',
    phase: 7,
    keywords: ['word', 'count', '단어', '문자', '통계'],
  },

  {
    id: 'jwt-decoder',
    title: 'JWT 디코더',
    description: 'JWT 토큰을 헤더·페이로드·시그니처로 분해합니다.',
    href: '/tools/dev/jwt',
    category: 'dev',
    icon: Key,
    status: 'ready',
    phase: 7,
    keywords: ['jwt', 'token', '토큰'],
  },
  {
    id: 'uuid-gen',
    title: 'UUID 생성',
    description: 'UUID v4 를 단일·대량 생성합니다.',
    href: '/tools/dev/uuid',
    category: 'dev',
    icon: Hexagon,
    status: 'ready',
    phase: 7,
    keywords: ['uuid', 'guid', '고유식별자'],
  },
  {
    id: 'password-gen',
    title: '비밀번호 생성',
    description: '안전한 랜덤 비밀번호를 생성하고 강도를 평가합니다.',
    href: '/tools/dev/password',
    category: 'dev',
    icon: KeyRound,
    status: 'ready',
    phase: 7,
    keywords: ['password', 'random', '비밀번호'],
  },
  {
    id: 'url-encoder',
    title: 'URL 인코더/디코더',
    description: 'URL 구성요소를 인코딩/디코딩하고 쿼리 파라미터를 분석.',
    href: '/tools/dev/url',
    category: 'dev',
    icon: Link2,
    status: 'ready',
    phase: 7,
    keywords: ['url', 'encode', 'decode', 'query'],
  },

  // ---- 2026-05-22 추가 묶음 (이미지·문서·개발자·유틸) ----
  {
    id: 'image-heic-to-jpg',
    title: 'HEIC → JPG',
    description: 'iPhone HEIC 사진을 JPG/PNG 로 변환합니다.',
    href: '/tools/image/heic-to-jpg',
    category: 'image',
    icon: FileImage,
    status: 'ready',
    phase: 7,
    keywords: ['heic', 'jpg', 'png', 'iphone', '아이폰', '사진', '변환', 'convert'],
  },
  {
    id: 'image-svg-to-png',
    title: 'SVG → PNG',
    description: '벡터 SVG 를 원하는 해상도의 PNG 로 래스터화합니다.',
    href: '/tools/image/svg-to-png',
    category: 'image',
    icon: FileImage,
    status: 'ready',
    phase: 7,
    keywords: ['svg', 'png', 'raster', '래스터', '벡터', 'convert', '변환'],
  },
  {
    id: 'image-exif-view',
    title: 'EXIF 뷰어',
    description: '사진의 촬영 정보·GPS·카메라 정보를 표시합니다.',
    href: '/tools/image/exif-view',
    category: 'image',
    icon: Info,
    status: 'ready',
    phase: 7,
    keywords: ['exif', 'metadata', '메타데이터', '촬영정보', 'gps', '카메라'],
  },
  {
    id: 'image-exif-strip',
    title: 'EXIF 제거',
    description: '사진의 위치·촬영 정보를 제거합니다 (개인정보 보호).',
    href: '/tools/image/exif-strip',
    category: 'image',
    icon: ShieldOff,
    status: 'ready',
    phase: 7,
    keywords: ['exif', 'strip', 'privacy', '제거', '개인정보', '위치', 'gps'],
  },

  {
    id: 'docx-to-pdf',
    title: 'DOCX → PDF',
    description: 'Word 문서를 PDF 로 변환합니다.',
    href: '/tools/docs/docx-to-pdf',
    category: 'docs',
    icon: FileText,
    status: 'ready',
    phase: 7,
    keywords: ['docx', 'pdf', 'word', '워드', '문서', 'convert', '변환'],
  },
  {
    id: 'docx-to-md',
    title: 'DOCX → Markdown',
    description: 'Word 문서를 Markdown 으로 변환합니다.',
    href: '/tools/docs/docx-to-md',
    category: 'docs',
    icon: FileText,
    status: 'ready',
    phase: 7,
    keywords: ['docx', 'markdown', 'md', 'word', '워드', 'convert', '변환'],
  },

  {
    id: 'color-converter',
    title: '색상 변환기',
    description: 'HEX / RGB / HSL / OKLCH 색상 표기 상호 변환.',
    href: '/tools/dev/color',
    category: 'dev',
    icon: Droplet,
    status: 'ready',
    phase: 7,
    keywords: ['color', '색상', 'hex', 'rgb', 'hsl', 'oklch', 'convert', '변환'],
  },
  {
    id: 'timestamp-converter',
    title: '타임스탬프 변환',
    description: 'Unix 타임스탬프와 ISO/로컬 시각을 상호 변환합니다.',
    href: '/tools/dev/timestamp',
    category: 'dev',
    icon: Clock,
    status: 'ready',
    phase: 7,
    keywords: ['timestamp', 'unix', 'epoch', 'date', 'iso', '시간', '날짜'],
  },
  {
    id: 'lorem-ipsum',
    title: 'Lorem Ipsum 생성',
    description: '더미 텍스트(단어·문장·문단)를 즉시 생성합니다.',
    href: '/tools/dev/lorem',
    category: 'dev',
    icon: Type,
    status: 'ready',
    phase: 7,
    keywords: ['lorem', 'ipsum', '더미', 'dummy', 'placeholder', '플레이스홀더'],
  },

  {
    id: 'unit-converter',
    title: '단위 변환기',
    description: '길이·무게·온도·면적·속도 등 일상 단위 상호 변환.',
    href: '/tools/util/unit',
    category: 'util',
    icon: Ruler,
    status: 'ready',
    phase: 7,
    keywords: ['unit', 'convert', '단위', '변환', '길이', '무게', '온도', '면적', '속도'],
  },
];

/** status:'ready' 만 반환 */
export const readyTools = () => TOOLS.filter((t) => t.status === 'ready');

/** 검색 쿼리 + 카테고리 필터 적용 */
export function filterTools(query: string, category: ToolCategory | 'all'): ToolMeta[] {
  const q = query.trim().toLowerCase();
  return TOOLS.filter((t) => {
    if (category !== 'all' && t.category !== category) return false;
    if (!q) return true;
    const hay = [
      t.title,
      t.description,
      ...(t.keywords ?? []),
    ]
      .join(' ')
      .toLowerCase();
    return hay.includes(q);
  }).sort((a, b) => {
    // ready 우선, 그 다음 phase 오름차순
    if (a.status !== b.status) return a.status === 'ready' ? -1 : 1;
    return a.phase - b.phase;
  });
}
