/**
 * 도구 레지스트리. 허브 페이지가 이 목록으로 카드 그리드를 렌더.
 *
 * 새 도구 추가 시:
 *   1) 페이지 경로 (href) 에 맞게 app/tools/{slug}/page.tsx 생성
 *   2) 이 파일에 ToolMeta 를 push 하고 status: 'ready' 지정
 */

import type { LucideIcon } from 'lucide-react';
import { searchTools } from './search';
import {
  Archive,
  ArrowDownAZ,
  ArrowRightLeft,
  AudioLines,
  Barcode,
  BarChart3,
  BookMarked,
  BookOpen,
  BookPlus,
  Braces,
  CalendarClock,
  Clapperboard,
  Clock,
  Code2,
  Database,
  Crop,
  Diff,
  Droplet,
  Eraser,
  FastForward,
  FileEdit,
  FileImage,
  FileLock,
  FileMinus,
  FilePlus,
  FileSearch,
  FileText,
  FileVideo,
  Film,
  Fingerprint,
  FileCode,
  FilePen,
  Grid3X3,
  Hash as HashIcon,
  Hexagon,
  Image as ImageIcon,
  ImagePlus,
  Images,
  Info,
  Key,
  Keyboard,
  KeyRound,
  Languages,
  Layers,
  LayoutGrid,
  LetterText,
  Link2,
  ListTree,
  Lock,
  Maximize2,
  Merge,
  Music,
  Palette,
  PenTool,
  QrCode,
  Regex,
  Replace,
  RotateCw,
  Ruler,
  ScanText,
  Scissors,
  Search,
  Shield,
  ShieldCheck,
  ShieldOff,
  Shuffle,
  Sliders,
  Sparkles,
  SpellCheck,
  SplitSquareHorizontal,
  Stamp,
  Subtitles,
  Table,
  Type,
  Volume2,
  VolumeX,
  Wand2,
  Zap,
  Wallet,
  Coins,
  CalendarCheck,
  ReceiptText,
  Contact,
  IdCard,
  EyeOff,
  Sigma,
  ScanLine,
  FileSpreadsheet,
  ScanFace,
  Binary,
  Contrast,
  Blend,
  AppWindow,
  Smile,
  FlipHorizontal2,
  Grid2x2,
  FileDigit,
  Squircle,
  Gauge,
  MonitorPlay,
  ListX,
  RemoveFormatting,
  Link,
  ListOrdered,
  Columns3,
  Scale,
  Landmark,
  Ratio,
  TimerReset,
  Dices,
  KeySquare,
  CodeXml,
  CalendarPlus,
  Rewind,
  AudioWaveform,
  Mic,
} from 'lucide-react';

export type ToolCategory =
  | 'image'
  | 'pdf'
  | 'security'
  | 'ai'
  | 'video'
  | 'gif'
  | 'audio'
  | 'util'
  | 'docs'
  | 'text'
  | 'dev';
export type ToolStatus = 'ready' | 'planned';

export interface ToolMeta {
  id: string;
  title: string;
  description: string;
  href: string;
  category: ToolCategory;
  icon: LucideIcon;
  status: ToolStatus;
  /** 구현 Phase 로 정렬. 1 = 우선순위 최상위. */
  phase: 1 | 2 | 3 | 4 | 5 | 6 | 7;
  /** 검색에서 매칭될 추가 키워드 (한/영) */
  keywords?: string[];
  /** 도구가 registry 에 추가된 날짜 (ISO yyyy-mm-dd). NEW 배지·신규순 정렬에 사용. */
  addedAt?: string;
}

export const CATEGORY_LABELS: Record<ToolCategory | 'all', string> = {
  all: '전체',
  image: '이미지',
  pdf: 'PDF',
  video: '비디오',
  gif: 'GIF',
  audio: '오디오',
  docs: '문서 변환',
  text: '텍스트',
  dev: '개발자',
  util: '유틸',
  security: '보안',
  ai: 'AI',
};

export const TOOLS: ToolMeta[] = [
  // ---- Ready ----
  {
    id: 'compress',
    title: '파일 용량 줄이기',
    description: '이미지와 PDF 를 브라우저에서 압축합니다.',
    href: '/tools/compress',
    category: 'pdf',
    icon: Wand2,
    status: 'ready',
    phase: 1,
    keywords: ['압축', '용량', 'compress', 'shrink', 'reduce'],
  },

  // ---- Phase 1: 고빈도 PDF ----
  {
    id: 'pdf-merge',
    title: 'PDF 합치기',
    description: '여러 PDF 파일을 하나로 병합합니다.',
    href: '/tools/pdf/merge',
    category: 'pdf',
    icon: Merge,
    status: 'ready',
    phase: 1,
    keywords: ['merge', 'combine', '병합', 'pdf 합치기', 'pdf merge', '여러 pdf', 'join pdf', '문서 병합'],
  },
  {
    id: 'pdf-split',
    title: 'PDF 분할',
    description: '페이지 범위로 PDF 를 나눕니다.',
    href: '/tools/pdf/split',
    category: 'pdf',
    icon: SplitSquareHorizontal,
    status: 'ready',
    phase: 1,
    keywords: ['split', 'divide', '분할', '나누기', 'pdf split', 'pdf 분할', '페이지 범위', 'extract pages'],
  },
  {
    id: 'pdf-rotate',
    title: 'PDF 회전',
    description: 'PDF 의 선택한 페이지만 90·180·270도 회전해 새로 저장합니다. 가로/세로 스캔 혼합 문서를 정리할 때 유용합니다.',
    href: '/tools/pdf/rotate',
    category: 'pdf',
    icon: RotateCw,
    status: 'ready',
    phase: 1,
    keywords: ['rotate', 'turn', 'flip', '회전', '페이지회전', '90도', 'orientation'],
  },
  {
    id: 'pdf-organize',
    title: 'PDF 페이지 정리',
    description: '페이지 재정렬·삭제·복제를 썸네일로 처리합니다.',
    href: '/tools/pdf/organize',
    category: 'pdf',
    icon: Shuffle,
    status: 'ready',
    phase: 1,
    keywords: ['organize', 'reorder', 'delete', '정리', '순서'],
  },
  {
    id: 'pdf-to-jpg',
    title: 'PDF → JPG',
    description: '각 페이지를 JPG 이미지로 추출합니다.',
    href: '/tools/pdf/to-jpg',
    category: 'pdf',
    icon: FileImage,
    status: 'ready',
    phase: 1,
    keywords: ['extract', 'image', '이미지 추출', '변환', 'pdf to jpg', 'pdf를 이미지로', 'pdf jpg', '페이지 이미지'],
  },
  {
    id: 'pdf-from-jpg',
    title: 'JPG → PDF',
    description: '여러 장의 이미지(JPG·PNG·WebP·HEIC)를 순서대로 묶어 하나의 PDF 파일로 만듭니다.',
    href: '/tools/pdf/from-jpg',
    category: 'pdf',
    icon: FileText,
    status: 'ready',
    phase: 1,
    keywords: ['convert', 'combine', '이미지to PDF', '이미지묶기', 'jpg', 'png', 'webp', '변환', 'PDF로', 'image to pdf'],
  },
  {
    id: 'pdf-page-numbers',
    title: 'PDF 페이지 번호',
    description: '페이지 번호를 일괄 삽입합니다.',
    href: '/tools/pdf/page-numbers',
    category: 'pdf',
    icon: Layers,
    status: 'ready',
    phase: 1,
    keywords: ['number', 'paginate', '페이지번호', 'page number', '쪽번호', '번호 매기기', 'pagination'],
  },
  {
    id: 'pdf-watermark',
    title: 'PDF 워터마크',
    description: '텍스트/이미지 워터마크를 추가합니다.',
    href: '/tools/pdf/watermark',
    category: 'pdf',
    icon: Stamp,
    status: 'ready',
    phase: 1,
    keywords: ['watermark', '워터마크', 'pdf watermark', '스탬프', 'stamp', '도장', 'pdf 워터마크', '로고'],
  },
  {
    id: 'pdf-crop',
    title: 'PDF 여백 자르기',
    description: '페이지 박스를 잘라 여백을 제거합니다.',
    href: '/tools/pdf/crop',
    category: 'pdf',
    icon: Crop,
    status: 'ready',
    phase: 1,
    keywords: ['crop', 'trim', '여백', 'pdf crop', '여백 자르기', '여백 제거', 'margin', '페이지 자르기'],
  },

  // ---- 2026-05-23 PDF 대폭 확장 (변환·편집·분석) ----
  {
    id: 'pdf-to-txt',
    title: 'PDF → TXT',
    description: 'PDF 의 텍스트를 추출해 일반 텍스트 파일로 저장합니다.',
    href: '/tools/pdf/to-txt',
    category: 'pdf',
    icon: FileText,
    status: 'ready',
    phase: 1,
    keywords: ['pdf', 'txt', 'text', '텍스트', '추출', 'extract', '변환'],
  },
  {
    id: 'pdf-to-md',
    title: 'PDF → Markdown',
    description: '폰트 크기로 헤딩을 추정해 # / ## / ### 구조의 Markdown 으로 변환합니다.',
    href: '/tools/pdf/to-md',
    category: 'pdf',
    icon: FileText,
    status: 'ready',
    phase: 1,
    keywords: ['pdf', 'markdown', 'md', '변환', 'convert', 'heading'],
  },
  {
    id: 'pdf-to-html',
    title: 'PDF → HTML',
    description: 'PDF 텍스트를 헤딩·단락 구조의 HTML 페이지로 변환합니다.',
    href: '/tools/pdf/to-html',
    category: 'pdf',
    icon: Code2,
    status: 'ready',
    phase: 1,
    keywords: ['pdf', 'html', 'web', '웹', '변환', 'convert'],
  },
  {
    id: 'pdf-to-word',
    title: 'PDF → Word (.doc)',
    description: 'PDF 의 텍스트를 추출해 Word/한컴에서 열 수 있는 .doc 파일로 변환.',
    href: '/tools/pdf/to-word',
    category: 'pdf',
    icon: FileText,
    status: 'ready',
    phase: 1,
    keywords: ['pdf', 'word', 'doc', 'docx', '워드', '한컴', '변환', 'convert'],
  },
  {
    id: 'pdf-to-epub',
    title: 'PDF → EPUB',
    description: 'PDF 텍스트를 추출해 헤딩 단위로 챕터를 만든 EPUB 전자책으로 변환.',
    href: '/tools/pdf/to-epub',
    category: 'pdf',
    icon: BookPlus,
    status: 'ready',
    phase: 1,
    keywords: ['pdf', 'epub', '전자책', 'ebook', '변환', 'convert'],
  },
  {
    id: 'pdf-metadata',
    title: 'PDF 메타데이터 편집',
    description: '제목·저자·주제·키워드 등 PDF 메타데이터를 수정합니다.',
    href: '/tools/pdf/metadata',
    category: 'pdf',
    icon: FileEdit,
    status: 'ready',
    phase: 1,
    keywords: ['pdf', 'metadata', '메타데이터', 'title', 'author', '제목', '저자', '편집'],
  },
  {
    id: 'pdf-image-extract',
    title: 'PDF 이미지 추출',
    description: 'PDF 페이지에 삽입된 이미지를 PNG 로 추출해 ZIP 으로 저장.',
    href: '/tools/pdf/image-extract',
    category: 'pdf',
    icon: Images,
    status: 'ready',
    phase: 1,
    keywords: ['pdf', 'image', '이미지', 'extract', '추출', 'png'],
  },
  {
    id: 'pdf-insert',
    title: 'PDF 페이지 삽입',
    description: '다른 PDF 의 페이지를 원하는 위치(맨 앞·맨 뒤·특정 페이지 뒤) 에 삽입.',
    href: '/tools/pdf/insert',
    category: 'pdf',
    icon: FilePlus,
    status: 'ready',
    phase: 1,
    keywords: ['pdf', 'insert', '삽입', '추가', 'add', 'page', '페이지'],
  },
  {
    id: 'pdf-nup',
    title: 'PDF N-up 배치',
    description: '한 장에 2/4/6/9 페이지를 모아 인쇄·시안용 PDF 를 만듭니다.',
    href: '/tools/pdf/nup',
    category: 'pdf',
    icon: LayoutGrid,
    status: 'ready',
    phase: 1,
    keywords: ['pdf', 'nup', 'n-up', '인쇄', 'print', '2up', '4up', 'booklet'],
  },
  {
    id: 'pdf-compare',
    title: 'PDF 비교',
    description: '두 PDF 의 텍스트를 추출해 줄 단위로 차이점(diff) 을 표시합니다.',
    href: '/tools/pdf/compare',
    category: 'pdf',
    icon: Diff,
    status: 'ready',
    phase: 1,
    keywords: ['pdf', 'compare', 'diff', '비교', '차이', '대조'],
  },
  {
    id: 'pdf-form-fill',
    title: 'PDF 양식 채우기',
    description: 'PDF 의 AcroForm 텍스트·체크·라디오·드롭다운 필드를 채워 저장.',
    href: '/tools/pdf/form-fill',
    category: 'pdf',
    icon: FilePen,
    status: 'ready',
    phase: 1,
    keywords: ['pdf', 'form', '양식', 'fill', '채우기', 'acroform'],
  },
  {
    id: 'pdf-background',
    title: 'PDF 배경 추가',
    description: '모든 페이지에 배경 색상이나 이미지를 깔아 워터마크·노트 스타일로 만듭니다.',
    href: '/tools/pdf/background',
    category: 'pdf',
    icon: Palette,
    status: 'ready',
    phase: 1,
    keywords: ['pdf', 'background', '배경', 'watermark', '워터마크', '컬러', 'color'],
  },
  {
    id: 'pdf-stats',
    title: 'PDF 통계',
    description: '페이지·단어·문자·폰트·목차·메타데이터를 분석합니다.',
    href: '/tools/pdf/stats',
    category: 'pdf',
    icon: BarChart3,
    status: 'ready',
    phase: 1,
    keywords: ['pdf', 'stats', 'count', '통계', '단어', '분량', 'wordcount', '분석'],
  },
  {
    id: 'html-to-pdf',
    title: 'HTML → PDF',
    description: 'HTML 코드를 PDF 로 변환합니다. 한글 폰트·CSS·인라인 이미지 지원.',
    href: '/tools/pdf/from-html',
    category: 'pdf',
    icon: Code2,
    status: 'ready',
    phase: 1,
    keywords: ['html', 'pdf', 'convert', '변환', 'web', '웹'],
  },

  // ---- Phase 2: 이미지 ----
  {
    id: 'image-resize',
    title: '이미지 리사이즈',
    description: '픽셀/비율/목표 용량으로 크기를 조정합니다.',
    href: '/tools/image/resize',
    category: 'image',
    icon: Maximize2,
    status: 'ready',
    phase: 2,
    keywords: ['resize', '크기', '조정', 'image resize', '이미지 크기 조정', '사진 크기', 'scale', '픽셀 크기'],
  },
  {
    id: 'image-crop',
    title: '이미지 자르기',
    description: '드래그로 영역 지정, 비율 프리셋 지원.',
    href: '/tools/image/crop',
    category: 'image',
    icon: Scissors,
    status: 'ready',
    phase: 2,
    keywords: ['crop', '자르기', '이미지 자르기', 'image crop', 'trim', '잘라내기', '비율 자르기', '사진 자르기'],
  },
  {
    id: 'image-rotate',
    title: '이미지 회전/반전',
    description: '90/180/270도 회전 및 좌우·상하 반전.',
    href: '/tools/image/rotate',
    category: 'image',
    icon: RotateCw,
    status: 'ready',
    phase: 2,
    keywords: ['rotate', 'flip', '회전', '반전', 'image rotate', '이미지 회전', '90도', 'mirror'],
  },
  {
    id: 'image-convert',
    title: '이미지 포맷 변환',
    description: 'JPG/PNG/WebP/AVIF 간 변환. 다중 파일 지원.',
    href: '/tools/image/convert',
    category: 'image',
    icon: FileImage,
    status: 'ready',
    phase: 2,
    keywords: ['convert', 'format', '변환', 'webp', 'avif'],
  },
  {
    id: 'image-watermark',
    title: '이미지 워터마크',
    description: '이미지 위에 텍스트 또는 로고 이미지를 워터마크로 합성합니다. 위치·투명도·크기·회전을 자유롭게 조절할 수 있습니다.',
    href: '/tools/image/watermark',
    category: 'image',
    icon: Stamp,
    status: 'ready',
    phase: 2,
    keywords: ['watermark', 'logo', 'stamp', '워터마크', '로고', '텍스트', '서명', 'overlay'],
  },
  {
    id: 'image-batch-compress',
    title: '이미지 일괄 압축',
    description: '여러 장을 한 번에 압축하여 ZIP 으로 저장.',
    href: '/tools/image/batch-compress',
    category: 'image',
    icon: Archive,
    status: 'ready',
    phase: 2,
    keywords: ['batch', 'bulk', '일괄', 'zip', '이미지 일괄 압축', '여러 장 압축', 'batch compress', '사진 압축'],
  },

  // ---- Phase 3: 보안/편집 ----
  {
    id: 'pdf-unlock',
    title: 'PDF 잠금 해제',
    description: '편집/인쇄 제한 제거 또는 열람 암호 해제 (래스터화).',
    href: '/tools/pdf/unlock',
    category: 'security',
    icon: ShieldOff,
    status: 'ready',
    phase: 3,
    keywords: ['unlock', 'decrypt', '잠금', '암호해제', 'pdf unlock', 'pdf 암호 제거', 'remove password', '제한 해제'],
  },
  {
    id: 'pdf-protect',
    title: 'PDF 암호 설정',
    description: '열람·권한 암호와 세부 권한(인쇄·편집·복사 등) 설정.',
    href: '/tools/pdf/protect',
    category: 'security',
    icon: FileLock,
    status: 'ready',
    phase: 3,
    keywords: ['protect', 'encrypt', 'password', '암호설정', 'pdf 암호', 'pdf password', 'pdf 보호', '권한 설정'],
  },
  {
    id: 'pdf-sign',
    title: 'PDF 서명',
    description: '마우스/터치로 직접 서명하여 PDF 에 삽입합니다.',
    href: '/tools/pdf/sign',
    category: 'security',
    icon: PenTool,
    status: 'ready',
    phase: 3,
    keywords: ['sign', 'signature', '서명', 'pdf sign', 'pdf 서명', '전자서명', '사인', '계약서 서명'],
  },
  {
    id: 'pdf-repair',
    title: 'PDF 복구',
    description: '2단계 복구: 구조 복원 + 래스터 재조립 폴백.',
    href: '/tools/pdf/repair',
    category: 'security',
    icon: FilePlus,
    status: 'ready',
    phase: 3,
    keywords: ['repair', 'fix', '복구', 'pdf repair', 'pdf 복구', '손상 pdf', '파일 복원', 'recover'],
  },

  // ---- Phase 4: AI ----
  {
    id: 'ocr',
    title: 'OCR (이미지/PDF → 텍스트)',
    description: '한국어 포함 이미지·PDF 의 문자를 인식합니다. Tesseract 기반.',
    href: '/tools/ocr',
    category: 'ai',
    icon: ScanText,
    status: 'ready',
    phase: 4,
    keywords: ['ocr', 'text', '문자', '추출', 'tesseract'],
  },
  {
    id: 'remove-background',
    title: 'AI 배경 제거',
    description: '인물·상품 배경을 자동 분리. 투명 배경 PNG 출력.',
    href: '/tools/image/remove-background',
    category: 'ai',
    icon: Eraser,
    status: 'ready',
    phase: 4,
    keywords: ['background', 'bg', '배경', '누끼', 'remove background', '배경 제거', '배경 투명', '투명 배경'],
  },
  {
    id: 'blur-face',
    title: '얼굴·번호판 가리기',
    description: 'AI 얼굴 자동 감지 + 블러·모자이크·이모지·검은막대. 폴더 일괄·반전·번호판 모드.',
    href: '/tools/image/blur-face',
    category: 'ai',
    icon: FileSearch,
    status: 'ready',
    phase: 4,
    keywords: ['face', 'blur', 'privacy', '모자이크', 'mosaic', '이모지', '번호판', '익명', 'censor', 'redact', '가리기', '폴더', '일괄', 'batch', '단체사진'],
  },
  {
    id: 'image-upscale',
    title: 'AI 이미지 업스케일',
    description: 'ESRGAN 초해상도로 2x/3x/4x 확대. 1MP 이하 권장.',
    href: '/tools/image/upscale',
    category: 'ai',
    icon: FileMinus,
    status: 'ready',
    phase: 4,
    keywords: ['upscale', 'enlarge', '확대', '업스케일', 'esrgan', 'sr'],
  },

  // ---- Phase 5: 비디오 & GIF (FFmpeg.wasm) ----
  {
    id: 'video-to-gif',
    title: '비디오 → GIF',
    description: '비디오의 구간을 GIF 애니메이션으로 변환합니다.',
    href: '/tools/video/to-gif',
    category: 'video',
    icon: Clapperboard,
    status: 'ready',
    phase: 5,
    keywords: ['gif', 'animation', 'ffmpeg', 'video', 'mp4'],
  },
  {
    id: 'video-convert',
    title: '비디오 포맷 변환',
    description: 'MP4 / WebM / MOV / AVI / MKV 상호 변환.',
    href: '/tools/video/convert',
    category: 'video',
    icon: FileVideo,
    status: 'ready',
    phase: 5,
    keywords: ['convert', 'format', 'mp4', 'webm', 'avi'],
  },
  {
    id: 'video-trim',
    title: '비디오 자르기',
    description: '시작·종료 시각을 지정해 비디오의 특정 구간만 잘라 새 파일로 저장합니다. 재인코딩 없이 빠르게 분할됩니다.',
    href: '/tools/video/trim',
    category: 'video',
    icon: Scissors,
    status: 'ready',
    phase: 5,
    keywords: ['trim', 'cut', 'splice', 'segment', '비디오자르기', '구간', '편집', '동영상자르기'],
  },
  {
    id: 'video-compress',
    title: '비디오 압축',
    description: '해상도·비트레이트 조정으로 용량을 줄입니다.',
    href: '/tools/video/compress',
    category: 'video',
    icon: Archive,
    status: 'ready',
    phase: 5,
    keywords: ['compress', 'shrink', '압축', '용량', 'video compress', '비디오 압축', '동영상 용량 줄이기', '영상 압축'],
  },
  {
    id: 'video-extract-frames',
    title: '비디오 → 프레임 추출',
    description: '각 프레임을 이미지로 추출합니다.',
    href: '/tools/video/extract-frames',
    category: 'video',
    icon: Film,
    status: 'ready',
    phase: 5,
    keywords: ['frames', 'extract', '프레임', '스틸', 'extract frames', '프레임 추출', '동영상 캡처', 'video to image'],
  },

  {
    id: 'gif-maker',
    title: 'GIF 만들기',
    description: '여러 이미지를 순서대로 애니메이션 GIF 로 묶습니다.',
    href: '/tools/gif/maker',
    category: 'gif',
    icon: Images,
    status: 'ready',
    phase: 5,
    keywords: ['gif', 'animate', 'maker', '만들기', 'gif maker', 'gif 만들기', '이미지로 gif', '움짤 만들기'],
  },
  {
    id: 'gif-resize',
    title: 'GIF 리사이즈',
    description: 'GIF 의 가로·세로 크기를 비율 유지 또는 자유 비율로 변경합니다. 해상도를 줄여 용량을 함께 절감할 수 있습니다.',
    href: '/tools/gif/resize',
    category: 'gif',
    icon: Maximize2,
    status: 'ready',
    phase: 5,
    keywords: ['resize', 'scale', 'dimension', '크기', '해상도', '비율', 'gif size'],
  },
  {
    id: 'gif-optimize',
    title: 'GIF 최적화',
    description: '팔레트·프레임 드롭으로 용량을 줄입니다.',
    href: '/tools/gif/optimize',
    category: 'gif',
    icon: Archive,
    status: 'ready',
    phase: 5,
    keywords: ['optimize', 'compress', '최적화', '용량', 'gif optimize', 'gif 압축', 'gif 용량 줄이기', '움짤 최적화'],
  },
  {
    id: 'gif-crop',
    title: 'GIF 영역 자르기',
    description: 'GIF 의 특정 영역만 잘라냅니다.',
    href: '/tools/gif/crop',
    category: 'gif',
    icon: Crop,
    status: 'ready',
    phase: 5,
    keywords: ['crop', '자르기', 'gif crop', 'gif 자르기', '영역 자르기', '움짤 자르기', 'trim', '잘라내기'],
  },
  {
    id: 'gif-trim',
    title: 'GIF 구간 자르기',
    description: 'GIF 의 시작·끝 시간을 지정해 원하는 구간만 잘라 새 GIF 로 저장합니다. 앞뒤 불필요한 프레임을 제거할 때 유용합니다.',
    href: '/tools/gif/trim',
    category: 'gif',
    icon: Scissors,
    status: 'ready',
    phase: 5,
    keywords: ['trim', 'cut', 'segment', '구간', '자르기', 'gif trim', '프레임'],
  },
  {
    id: 'gif-effects',
    title: 'GIF 효과',
    description: '역재생 · 배속 · 핑퐁 반복 효과를 적용합니다.',
    href: '/tools/gif/effects',
    category: 'gif',
    icon: FastForward,
    status: 'ready',
    phase: 5,
    keywords: ['reverse', 'speed', '역재생', '배속', 'pingpong'],
  },
  {
    id: 'gif-text',
    title: 'GIF 텍스트 삽입',
    description: 'GIF 전체에 표시될 텍스트·자막을 추가합니다.',
    href: '/tools/gif/text',
    category: 'gif',
    icon: Type,
    status: 'ready',
    phase: 5,
    keywords: ['text', 'caption', '자막', 'gif text', 'gif 자막', '움짤 텍스트', '텍스트 삽입', '캡션'],
  },

  // ---- Phase 6: 오디오 & 유틸리티 ----
  {
    id: 'video-to-audio',
    title: '비디오 → MP3 (오디오 추출)',
    description: '비디오 파일에서 오디오 트랙을 추출하여 MP3/WAV 로 저장.',
    href: '/tools/audio/from-video',
    category: 'audio',
    icon: Music,
    status: 'ready',
    phase: 6,
    keywords: ['audio', 'extract', 'mp3', '오디오추출', '음원'],
  },
  {
    id: 'audio-convert',
    title: '오디오 포맷 변환',
    description: 'MP3 / WAV / OGG / AAC / M4A / FLAC 상호 변환.',
    href: '/tools/audio/convert',
    category: 'audio',
    icon: Volume2,
    status: 'ready',
    phase: 6,
    keywords: ['convert', 'mp3', 'wav', 'flac', '변환'],
  },
  {
    id: 'audio-trim',
    title: '오디오 자르기',
    description: '시작·끝 시각을 지정해 오디오 파일의 원하는 구간만 잘라 새 파일로 저장합니다. MP3·WAV·OGG 등 대부분 포맷을 지원합니다.',
    href: '/tools/audio/trim',
    category: 'audio',
    icon: Scissors,
    status: 'ready',
    phase: 6,
    keywords: ['trim', 'cut', 'splice', 'segment', '오디오자르기', '구간', '편집', 'audio cut'],
  },
  {
    id: 'audio-compress',
    title: '오디오 압축',
    description: '비트레이트를 낮춰 오디오 용량을 줄입니다.',
    href: '/tools/audio/compress',
    category: 'audio',
    icon: Archive,
    status: 'ready',
    phase: 6,
    keywords: ['compress', 'bitrate', '압축', '용량', 'audio compress', '오디오 압축', '음원 용량 줄이기', 'mp3 압축'],
  },

  {
    id: 'qr-code',
    title: 'QR 코드 생성/읽기',
    description: '텍스트·URL → QR 생성, 이미지 → QR 해독.',
    href: '/tools/util/qr',
    category: 'util',
    icon: QrCode,
    status: 'ready',
    phase: 6,
    keywords: ['qr', 'qrcode', '큐알', 'qr code', 'qr 생성', 'qr 스캔', '큐알코드', 'qr reader'],
  },
  {
    id: 'barcode',
    title: '바코드 생성',
    description: 'Code128 / EAN / UPC 바코드를 생성합니다.',
    href: '/tools/util/barcode',
    category: 'util',
    icon: Barcode,
    status: 'ready',
    phase: 6,
    keywords: ['barcode', '바코드', 'barcode generator', '바코드 생성', 'code128', 'ean', 'upc', '바코드 만들기'],
  },
  {
    id: 'color-palette',
    title: '이미지 색상 팔레트',
    description: '이미지에서 주요 색상을 추출합니다.',
    href: '/tools/util/palette',
    category: 'util',
    icon: Palette,
    status: 'ready',
    phase: 6,
    keywords: ['color', 'palette', '색상', '팔레트', 'color palette', '색상 추출', '대표 색상', '이미지 색상'],
  },
  {
    id: 'file-hash',
    title: '파일 해시',
    description: 'SHA-1/256/512 · MD5 해시를 계산합니다.',
    href: '/tools/util/hash',
    category: 'util',
    icon: Fingerprint,
    status: 'ready',
    phase: 6,
    keywords: ['hash', 'sha', 'md5', '해시', '체크섬'],
  },
  {
    id: 'json-format',
    title: 'JSON 포맷터',
    description: 'JSON 포맷팅·압축·검증·트리 뷰.',
    href: '/tools/util/json',
    category: 'util',
    icon: Braces,
    status: 'ready',
    phase: 6,
    keywords: ['json', 'format', 'validate', '포맷팅', 'json formatter', 'json 정렬', 'json 검증', 'beautify', 'json 트리'],
  },
  {
    id: 'base64',
    title: 'Base64 인코딩',
    description: '텍스트·파일을 Base64 로 인코딩하거나 다시 디코딩합니다. data URI·이미지 임베드·API 전송 사전 처리에 사용합니다.',
    href: '/tools/util/base64',
    category: 'util',
    icon: FileCode,
    status: 'ready',
    phase: 6,
    keywords: ['base64', 'encode', 'decode', '인코딩', '디코딩', '변환', 'data uri', '이미지base64'],
  },

  // ---- Phase 7: 문서 변환 / 텍스트 / 개발자 도구 ----
  {
    id: 'md-html',
    title: 'Markdown ↔ HTML',
    description: 'Markdown 과 HTML 상호 변환, 미리보기 포함.',
    href: '/tools/docs/md-html',
    category: 'docs',
    icon: FileText,
    status: 'ready',
    phase: 7,
    keywords: ['markdown', 'md', 'html', 'convert', '마크다운', '변환', 'md to html', 'html to md'],
  },
  {
    id: 'csv-json',
    title: 'CSV ↔ JSON',
    description: '스프레드시트 데이터를 JSON 으로 변환하거나 반대로.',
    href: '/tools/docs/csv-json',
    category: 'docs',
    icon: Table,
    status: 'ready',
    phase: 7,
    keywords: ['csv', 'json', 'tsv', '스프레드시트', 'csv to json', 'json to csv', '변환', 'csv 변환'],
  },
  {
    id: 'yaml-json',
    title: 'YAML ↔ JSON',
    description: 'YAML 과 JSON 상호 변환.',
    href: '/tools/docs/yaml-json',
    category: 'docs',
    icon: FileCode,
    status: 'ready',
    phase: 7,
    keywords: ['yaml', 'json', 'convert', '변환', 'yaml to json', 'json to yaml', 'yml', 'yaml 변환'],
  },
  {
    id: 'epub-to-pdf',
    title: 'EPUB → PDF',
    description: 'EPUB 전자책을 PDF 로 변환합니다. 50 MB 이하 권장.',
    href: '/tools/docs/epub-to-pdf',
    category: 'docs',
    icon: BookOpen,
    status: 'ready',
    phase: 7,
    keywords: ['epub', 'pdf', '전자책', 'ebook', 'convert', '변환', '책'],
  },
  {
    id: 'epub-reader',
    title: 'EPUB 리더',
    description: 'EPUB 전자책을 브라우저에서 바로 읽습니다. 목차·테마·글자 크기 조절.',
    href: '/tools/docs/epub-reader',
    category: 'docs',
    icon: BookOpen,
    status: 'ready',
    phase: 7,
    keywords: ['epub', '리더', 'reader', 'view', '뷰어', '읽기', 'ebook', '전자책'],
  },
  {
    id: 'epub-metadata',
    title: 'EPUB 메타데이터 편집',
    description: '제목·저자·언어·설명·태그 등 EPUB 메타데이터를 편집합니다.',
    href: '/tools/docs/epub-metadata',
    category: 'docs',
    icon: FileEdit,
    status: 'ready',
    phase: 7,
    keywords: ['epub', 'metadata', '메타데이터', 'title', 'author', '제목', '저자', '편집', 'edit'],
  },
  {
    id: 'epub-cover-extract',
    title: 'EPUB 표지 추출',
    description: 'EPUB 의 표지 이미지를 원본 그대로 꺼냅니다.',
    href: '/tools/docs/epub-cover-extract',
    category: 'docs',
    icon: ImageIcon,
    status: 'ready',
    phase: 7,
    keywords: ['epub', 'cover', '표지', 'extract', '추출', '커버'],
  },
  {
    id: 'epub-cover-replace',
    title: 'EPUB 표지 교체',
    description: 'EPUB 의 표지 이미지를 새 그림으로 교체합니다.',
    href: '/tools/docs/epub-cover-replace',
    category: 'docs',
    icon: ImagePlus,
    status: 'ready',
    phase: 7,
    keywords: ['epub', 'cover', '표지', 'replace', '교체', '변경', '커버'],
  },
  {
    id: 'epub-to-txt',
    title: 'EPUB → TXT',
    description: 'EPUB 본문을 일반 텍스트 파일로 변환합니다.',
    href: '/tools/docs/epub-to-txt',
    category: 'docs',
    icon: FileText,
    status: 'ready',
    phase: 7,
    keywords: ['epub', 'txt', 'text', '텍스트', '변환', 'convert', '책'],
  },
  {
    id: 'epub-to-md',
    title: 'EPUB → Markdown',
    description: 'EPUB 챕터를 Markdown 으로 변환. 단일 파일 또는 챕터별 ZIP.',
    href: '/tools/docs/epub-to-md',
    category: 'docs',
    icon: FileText,
    status: 'ready',
    phase: 7,
    keywords: ['epub', 'markdown', 'md', '변환', 'convert'],
  },
  {
    id: 'epub-to-html',
    title: 'EPUB → HTML',
    description: 'EPUB 을 단일 HTML(이미지 인라인) 또는 챕터별 HTML ZIP 으로 변환.',
    href: '/tools/docs/epub-to-html',
    category: 'docs',
    icon: Code2,
    status: 'ready',
    phase: 7,
    keywords: ['epub', 'html', '변환', 'convert', 'web'],
  },
  {
    id: 'epub-images-extract',
    title: 'EPUB 이미지 추출',
    description: 'EPUB 안의 모든 이미지(표지·삽화) 를 ZIP 으로 추출합니다.',
    href: '/tools/docs/epub-images-extract',
    category: 'docs',
    icon: Images,
    status: 'ready',
    phase: 7,
    keywords: ['epub', 'image', '이미지', 'extract', '추출', '삽화'],
  },
  {
    id: 'epub-split',
    title: 'EPUB 챕터 분할',
    description: 'EPUB 의 챕터를 각각 독립된 EPUB 으로 분할해 ZIP 으로 묶습니다.',
    href: '/tools/docs/epub-split',
    category: 'docs',
    icon: SplitSquareHorizontal,
    status: 'ready',
    phase: 7,
    keywords: ['epub', 'split', '분할', '챕터', 'chapter', '나누기'],
  },
  {
    id: 'epub-merge',
    title: 'EPUB 병합',
    description: '여러 EPUB 을 순서대로 하나의 EPUB 으로 묶습니다.',
    href: '/tools/docs/epub-merge',
    category: 'docs',
    icon: Merge,
    status: 'ready',
    phase: 7,
    keywords: ['epub', 'merge', 'combine', '병합', '합치기', 'join'],
  },
  {
    id: 'epub-compress',
    title: 'EPUB 압축',
    description: 'EPUB 안의 이미지를 재인코딩·축소해 전체 용량을 줄입니다.',
    href: '/tools/docs/epub-compress',
    category: 'docs',
    icon: Archive,
    status: 'ready',
    phase: 7,
    keywords: ['epub', 'compress', '압축', '용량', 'optimize', '최적화'],
  },
  {
    id: 'txt-to-epub',
    title: '텍스트 → EPUB',
    description: 'TXT 또는 입력한 텍스트를 EPUB 전자책으로 만듭니다.',
    href: '/tools/docs/txt-to-epub',
    category: 'docs',
    icon: BookPlus,
    status: 'ready',
    phase: 7,
    keywords: ['txt', 'epub', '생성', '만들기', 'create', 'ebook', '전자책'],
  },
  {
    id: 'md-to-epub',
    title: 'Markdown → EPUB',
    description: 'Markdown 을 헤딩 단위로 챕터 분할해 EPUB 으로 만듭니다. 표지 포함 가능.',
    href: '/tools/docs/md-to-epub',
    category: 'docs',
    icon: BookPlus,
    status: 'ready',
    phase: 7,
    keywords: ['markdown', 'md', 'epub', '생성', 'create', 'ebook', '전자책'],
  },
  {
    id: 'epub-stats',
    title: 'EPUB 통계',
    description: '단어·문자·챕터·이미지 수와 챕터별 분량을 분석합니다.',
    href: '/tools/docs/epub-stats',
    category: 'docs',
    icon: BarChart3,
    status: 'ready',
    phase: 7,
    keywords: ['epub', 'stats', 'count', '통계', '단어', '분량', 'wordcount'],
  },
  {
    id: 'epub-validate',
    title: 'EPUB 구조 검증',
    description: 'OPF·spine·manifest·표지·자산 누락 등 EPUB 구조를 점검합니다.',
    href: '/tools/docs/epub-validate',
    category: 'docs',
    icon: ShieldCheck,
    status: 'ready',
    phase: 7,
    keywords: ['epub', 'validate', 'check', '검증', '검사', '구조', 'lint'],
  },

  {
    id: 'regex-tester',
    title: '정규식 테스터',
    description: '정규식을 실시간으로 테스트하고 매칭 결과를 확인.',
    href: '/tools/text/regex',
    category: 'text',
    icon: Regex,
    status: 'ready',
    phase: 7,
    keywords: ['regex', 'regexp', '정규식', 'pattern', 'regex tester', '정규표현식', '패턴 테스트', '매칭'],
  },
  {
    id: 'text-diff',
    title: '텍스트 비교 (Diff)',
    description: '두 텍스트의 차이를 줄 단위로 비교합니다.',
    href: '/tools/text/diff',
    category: 'text',
    icon: Diff,
    status: 'ready',
    phase: 7,
    keywords: ['diff', 'compare', '비교', 'text diff', '텍스트 비교', '차이', '줄 비교', '대조'],
  },
  {
    id: 'text-count',
    title: '단어·문자 카운트',
    description: '단어/문자/줄/바이트 수를 실시간 집계합니다.',
    href: '/tools/text/count',
    category: 'text',
    icon: HashIcon,
    status: 'ready',
    phase: 7,
    keywords: ['word', 'count', '단어', '문자', '통계'],
  },

  {
    id: 'jwt-decoder',
    title: 'JWT 디코더',
    description: 'JWT 토큰을 헤더·페이로드·시그니처로 분해합니다.',
    href: '/tools/dev/jwt',
    category: 'dev',
    icon: Key,
    status: 'ready',
    phase: 7,
    keywords: ['jwt', 'token', '토큰', 'jwt decoder', 'jwt 디코드', 'jwt 파싱', '페이로드', 'decode'],
  },
  {
    id: 'uuid-gen',
    title: 'UUID 생성',
    description: 'UUID v4 를 단일·대량 생성합니다.',
    href: '/tools/dev/uuid',
    category: 'dev',
    icon: Hexagon,
    status: 'ready',
    phase: 7,
    keywords: ['uuid', 'guid', '고유식별자', 'uuid generator', 'uuid 생성', 'v4', '랜덤 id', '식별자'],
  },
  {
    id: 'password-gen',
    title: '비밀번호 생성',
    description: '안전한 랜덤 비밀번호를 생성하고 강도를 평가합니다.',
    href: '/tools/dev/password',
    category: 'dev',
    icon: KeyRound,
    status: 'ready',
    phase: 7,
    keywords: ['password', 'random', '비밀번호', 'password generator', '비밀번호 생성', '랜덤 암호', '강력한 비밀번호', 'passwd'],
  },
  {
    id: 'url-encoder',
    title: 'URL 인코더/디코더',
    description: 'URL 구성요소를 인코딩/디코딩하고 쿼리 파라미터를 분석.',
    href: '/tools/dev/url',
    category: 'dev',
    icon: Link2,
    status: 'ready',
    phase: 7,
    keywords: ['url', 'encode', 'decode', 'query', 'url encode', 'url 인코딩', '퍼센트 인코딩', '쿼리 파라미터'],
  },

  // ---- 2026-05-22 추가 묶음 (이미지·문서·개발자·유틸) ----
  {
    id: 'image-heic-to-jpg',
    title: 'HEIC → JPG',
    description: 'iPhone HEIC 사진을 JPG/PNG 로 변환합니다.',
    href: '/tools/image/heic-to-jpg',
    category: 'image',
    icon: FileImage,
    status: 'ready',
    phase: 7,
    keywords: ['heic', 'jpg', 'png', 'iphone', '아이폰', '사진', '변환', 'convert'],
  },
  {
    id: 'image-svg-to-png',
    title: 'SVG → PNG',
    description: '벡터 SVG 를 원하는 해상도의 PNG 로 래스터화합니다.',
    href: '/tools/image/svg-to-png',
    category: 'image',
    icon: FileImage,
    status: 'ready',
    phase: 7,
    keywords: ['svg', 'png', 'raster', '래스터', '벡터', 'convert', '변환'],
  },
  {
    id: 'image-exif-view',
    title: 'EXIF 뷰어',
    description: '사진의 촬영 정보·GPS·카메라 정보를 표시합니다.',
    href: '/tools/image/exif-view',
    category: 'image',
    icon: Info,
    status: 'ready',
    phase: 7,
    keywords: ['exif', 'metadata', '메타데이터', '촬영정보', 'gps', '카메라'],
  },
  {
    id: 'image-exif-strip',
    title: 'EXIF 제거',
    description: '사진의 위치·촬영 정보를 제거합니다 (개인정보 보호).',
    href: '/tools/image/exif-strip',
    category: 'image',
    icon: ShieldOff,
    status: 'ready',
    phase: 7,
    keywords: ['exif', 'strip', 'privacy', '제거', '개인정보', '위치', 'gps'],
  },

  {
    id: 'docx-to-pdf',
    title: 'DOCX → PDF',
    description: 'Word 문서를 PDF 로 변환합니다.',
    href: '/tools/docs/docx-to-pdf',
    category: 'docs',
    icon: FileText,
    status: 'ready',
    phase: 7,
    keywords: ['docx', 'pdf', 'word', '워드', '문서', 'convert', '변환'],
  },
  {
    id: 'docx-to-md',
    title: 'DOCX → Markdown',
    description: 'Word 문서를 Markdown 으로 변환합니다.',
    href: '/tools/docs/docx-to-md',
    category: 'docs',
    icon: FileText,
    status: 'ready',
    phase: 7,
    keywords: ['docx', 'markdown', 'md', 'word', '워드', 'convert', '변환'],
  },

  {
    id: 'color-converter',
    title: '색상 변환기',
    description: 'HEX / RGB / HSL / OKLCH 색상 표기 상호 변환.',
    href: '/tools/dev/color',
    category: 'dev',
    icon: Droplet,
    status: 'ready',
    phase: 7,
    keywords: ['color', '색상', 'hex', 'rgb', 'hsl', 'oklch', 'convert', '변환'],
  },
  {
    id: 'timestamp-converter',
    title: '타임스탬프 변환',
    description: 'Unix 타임스탬프와 ISO/로컬 시각을 상호 변환합니다.',
    href: '/tools/dev/timestamp',
    category: 'dev',
    icon: Clock,
    status: 'ready',
    phase: 7,
    keywords: ['timestamp', 'unix', 'epoch', 'date', 'iso', '시간', '날짜'],
  },
  {
    id: 'lorem-ipsum',
    title: 'Lorem Ipsum 생성',
    description: '더미 텍스트(단어·문장·문단)를 즉시 생성합니다.',
    href: '/tools/dev/lorem',
    category: 'dev',
    icon: Type,
    status: 'ready',
    phase: 7,
    keywords: ['lorem', 'ipsum', '더미', 'dummy', 'placeholder', '플레이스홀더'],
  },

  {
    id: 'unit-converter',
    title: '단위 변환기',
    description: '길이·무게·온도·면적·속도 등 일상 단위 상호 변환.',
    href: '/tools/util/unit',
    category: 'util',
    icon: Ruler,
    status: 'ready',
    phase: 7,
    keywords: ['unit', 'convert', '단위', '변환', '길이', '무게', '온도', '면적', '속도'],
  },

  // ---- 2026-05-23 추가 묶음 (텍스트·오디오·보안 보강) ----
  {
    id: 'text-case',
    title: '대소문자·케이스 변환',
    description: 'UPPER · lower · Title · camelCase · snake_case 등 12종 즉시 변환.',
    href: '/tools/text/case',
    category: 'text',
    icon: ArrowRightLeft,
    status: 'ready',
    phase: 7,
    keywords: ['case', '대소문자', 'upper', 'lower', 'camel', 'snake', 'kebab', 'pascal', '변환'],
  },
  {
    id: 'text-sort',
    title: '줄 정렬·중복 제거',
    description: '여러 줄을 정렬·역순·랜덤·중복 제거. 한국어·숫자 인식.',
    href: '/tools/text/sort',
    category: 'text',
    icon: ArrowDownAZ,
    status: 'ready',
    phase: 7,
    keywords: ['sort', 'dedupe', 'unique', '정렬', '중복', '제거', '줄', 'lines'],
  },
  {
    id: 'text-replace',
    title: '일괄 찾기·치환',
    description: '정규식·캡처 그룹 지원 일괄 치환. 매칭 개수 실시간 표시.',
    href: '/tools/text/replace',
    category: 'text',
    icon: Replace,
    status: 'ready',
    phase: 7,
    keywords: ['replace', 'find', 'substitute', '치환', '바꾸기', '찾기', 'regex', '정규식'],
  },
  {
    id: 'html-entities',
    title: 'HTML 엔티티 인·디코드',
    description: 'HTML 특수 문자(&, <, >, ©, ¡ 등)와 엔티티 표기를 양방향 변환합니다. 이름·숫자·16진수 엔티티를 모두 지원합니다.',
    href: '/tools/text/html-entities',
    category: 'text',
    icon: Code2,
    status: 'ready',
    phase: 7,
    keywords: ['html', 'entity', 'entities', '엔티티', 'encode', 'decode', 'escape', '특수문자'],
  },

  {
    id: 'audio-merge',
    title: '오디오 합치기',
    description: '여러 오디오 파일을 순서대로 이어붙입니다. 크로스페이드 지원.',
    href: '/tools/audio/merge',
    category: 'audio',
    icon: Merge,
    status: 'ready',
    phase: 7,
    keywords: ['merge', 'concat', 'join', '합치기', '이어붙이기', '연결'],
  },
  {
    id: 'audio-volume',
    title: '오디오 볼륨 조정',
    description: 'dB 단위 증감 또는 LUFS 라우드니스 정규화.',
    href: '/tools/audio/volume',
    category: 'audio',
    icon: Volume2,
    status: 'ready',
    phase: 7,
    keywords: ['volume', 'gain', 'loudness', 'normalize', 'lufs', '볼륨', '소리', '정규화'],
  },
  {
    id: 'audio-speed',
    title: '오디오 배속 조절',
    description: '0.25x~4x 속도 조절. 피치 유지 (atempo 필터).',
    href: '/tools/audio/speed',
    category: 'audio',
    icon: FastForward,
    status: 'ready',
    phase: 7,
    keywords: ['speed', 'tempo', 'rate', '배속', '속도', '느리게', '빠르게'],
  },

  {
    id: 'file-encrypt',
    title: '파일 암호화·복호화',
    description: 'AES-256-GCM + PBKDF2 로 어떤 파일이든 비밀번호 암호화.',
    href: '/tools/security/file-encrypt',
    category: 'security',
    icon: Lock,
    status: 'ready',
    phase: 7,
    keywords: ['encrypt', 'decrypt', 'aes', 'password', '암호화', '복호화', '비밀번호'],
  },
  {
    id: 'text-encrypt',
    title: '텍스트 암호화·복호화',
    description: 'AES-256-GCM 으로 메모·메시지를 비밀번호 암호화. Base64 출력.',
    href: '/tools/security/text-encrypt',
    category: 'security',
    icon: Shield,
    status: 'ready',
    phase: 7,
    keywords: ['encrypt', 'message', 'note', 'text', '암호화', '비밀', '메시지', 'aes'],
  },
  {
    id: 'pdf-flatten',
    title: 'PDF Flatten',
    description: '양식 입력값을 페이지에 고정하고 주석·링크를 제거해 인쇄·배포용으로 최종화합니다. 편집 가능한 필드를 모두 평탄화합니다.',
    href: '/tools/security/pdf-flatten',
    category: 'pdf',
    icon: Layers,
    status: 'ready',
    phase: 7,
    keywords: ['flatten', 'form', 'annotation', '평탄화', '양식', '주석', 'pdf', '인쇄', '최종화'],
  },

  {
    id: 'cron-explainer',
    title: 'cron 표현식 해석기',
    description: 'cron 5필드 표현식을 한국어로 풀고 다음 7회 실행 시각 표시.',
    href: '/tools/dev/cron',
    category: 'dev',
    icon: CalendarClock,
    status: 'ready',
    phase: 7,
    keywords: ['cron', 'crontab', 'schedule', 'expression', '크론', '스케줄', '표현식'],
  },

  // ---- 2026-05-24 6개 묶음 대확장 ----
  // 한국어 텍스트 8종
  { id: 'ko-spacing', title: '한글 띄어쓰기 교정', description: '자주 빠지는 띄어쓰기를 규칙으로 자동 교정.', href: '/tools/text/ko-spacing', category: 'text', icon: Type, status: 'ready', phase: 7, keywords: ['띄어쓰기', 'spacing', '한국어', '교정', 'korean'] },
  { id: 'ko-spellcheck', title: '한국어 맞춤법 검사', description: '자주 틀리는 단어를 표시하고 일괄 교정.', href: '/tools/text/ko-spellcheck', category: 'text', icon: SpellCheck, status: 'ready', phase: 7, keywords: ['맞춤법', 'spellcheck', '한국어', '검사', 'korean'] },
  { id: 'hanja', title: '한자 → 한글 변환', description: '한자를 한국 한자음으로 자동 변환.', href: '/tools/text/hanja', category: 'text', icon: Languages, status: 'ready', phase: 7, keywords: ['한자', 'hanja', '한글', 'hangul', '변환'] },
  { id: 'keyboard-flip', title: '한영 자판 변환', description: '한영키 잘못 누른 텍스트를 자동 변환 (dkssudgktpdy → 안녕하세요).', href: '/tools/text/keyboard-flip', category: 'text', icon: Keyboard, status: 'ready', phase: 7, keywords: ['한영', '자판', 'keyboard', '한영키', '변환'] },
  { id: 'jamo', title: '한글 자모 분해', description: '한글을 초성·중성·종성으로 풀어 표시.', href: '/tools/text/jamo', category: 'text', icon: Type, status: 'ready', phase: 7, keywords: ['자모', 'jamo', '초성', '중성', '종성', '한글'] },
  { id: 'manuscript-count', title: '원고지 글자 수 세기', description: '200/400자 원고지·신국판 출판 페이지 환산.', href: '/tools/text/manuscript-count', category: 'text', icon: FileText, status: 'ready', phase: 7, keywords: ['원고지', '글자수', '출판', '문학', '공모전'] },
  { id: 'ko-sort', title: '한국어 정렬·중복 제거', description: '한국어/숫자 인식 정렬·셔플·길이 정렬·중복 제거.', href: '/tools/text/ko-sort', category: 'text', icon: ArrowDownAZ, status: 'ready', phase: 7, keywords: ['정렬', 'sort', '가나다', '중복', '한국어'] },
  { id: 'syllable-spread', title: '한글 음절·자모 풀어쓰기', description: '한글을 음절 또는 자모 단위로 다양한 구분자로 풀어 표시.', href: '/tools/text/syllable-spread', category: 'text', icon: LetterText, status: 'ready', phase: 7, keywords: ['음절', '자모', '풀어쓰기', '띄어', '한글'] },

  // 데이터/스프레드시트 6종
  { id: 'xlsx-convert', title: 'XLSX ↔ CSV ↔ JSON', description: 'Excel·CSV·JSON 사이 자유 변환. 시트 선택 가능.', href: '/tools/docs/xlsx-convert', category: 'docs', icon: Table, status: 'ready', phase: 7, keywords: ['xlsx', 'excel', 'csv', 'json', '엑셀', '시트'] },
  { id: 'sql-format', title: 'SQL 포맷터', description: 'SQL 쿼리 들여쓰기·키워드 케이스. 10종 방언 지원.', href: '/tools/dev/sql-format', category: 'dev', icon: Database, status: 'ready', phase: 7, keywords: ['sql', 'format', 'pretty', '쿼리', 'mysql', 'postgres'] },
  { id: 'jsonpath', title: 'JSONPath 테스터', description: 'JSONPath 표현식으로 JSON 값 추출. 실시간 평가.', href: '/tools/dev/jsonpath', category: 'dev', icon: Search, status: 'ready', phase: 7, keywords: ['jsonpath', 'json', '쿼리', '추출', 'path'] },
  { id: 'json-xml', title: 'JSON ↔ XML', description: 'JSON 과 XML 간 상호 변환. 루트 태그 지정.', href: '/tools/dev/json-xml', category: 'dev', icon: ArrowRightLeft, status: 'ready', phase: 7, keywords: ['json', 'xml', 'convert', '변환', 'json to xml', 'xml to json', 'json xml', '상호 변환'] },
  { id: 'chart', title: '차트 → PNG', description: '막대·꺾은선·원그래프 데이터를 입력해 즉시 PNG 이미지로 생성합니다. 보고서·발표 자료에 바로 붙여 쓸 수 있습니다.', href: '/tools/dev/chart', category: 'util', icon: BarChart3, status: 'ready', phase: 7, keywords: ['chart', '차트', '그래프', 'bar', 'line', 'pie', 'png', '시각화', 'graph'] },
  { id: 'csv-diff', title: 'CSV 비교', description: '두 CSV 를 키 컬럼 기준 행 단위 비교. 추가·삭제·변경 표시.', href: '/tools/docs/csv-diff', category: 'docs', icon: Diff, status: 'ready', phase: 7, keywords: ['csv', 'diff', '비교', 'compare', 'csv diff', 'csv 비교', '행 비교', '데이터 비교'] },

  // PDF 고급 5종
  { id: 'pdf-search', title: '다중 PDF 검색', description: '여러 PDF 안에서 키워드를 한꺼번에 찾고 문맥 표시.', href: '/tools/pdf/search', category: 'pdf', icon: Search, status: 'ready', phase: 1, keywords: ['pdf', 'search', '검색', '다중', '키워드'] },
  { id: 'pdf-visual-diff', title: 'PDF 시각 비교', description: '두 PDF 의 같은 페이지를 픽셀 단위로 비교해 차이를 표시.', href: '/tools/pdf/visual-diff', category: 'pdf', icon: Diff, status: 'ready', phase: 1, keywords: ['pdf', 'visual', 'diff', '시각', '비교'] },
  { id: 'pdf-bookmarks', title: 'PDF 책갈피 보기', description: '목차/책갈피 트리 표시 + Markdown 으로 내보내기.', href: '/tools/pdf/bookmarks', category: 'pdf', icon: BookMarked, status: 'ready', phase: 1, keywords: ['pdf', 'bookmark', 'outline', '목차', '책갈피'] },
  { id: 'pdf-previews', title: 'PDF 페이지 PNG', description: '모든 페이지를 PNG/JPG 로 일괄 렌더해 ZIP 저장.', href: '/tools/pdf/previews', category: 'pdf', icon: Images, status: 'ready', phase: 1, keywords: ['pdf', 'preview', 'png', 'jpg', '썸네일', '페이지'] },
  { id: 'pdf-linearize', title: 'PDF 웹 최적화', description: '중복 객체 제거·압축 스트림 재구성으로 PDF 정리.', href: '/tools/pdf/linearize', category: 'pdf', icon: Zap, status: 'ready', phase: 1, keywords: ['pdf', 'linearize', 'optimize', '최적화', '웹'] },

  // 이미지 확장 8종
  { id: 'image-collage', title: '이미지 콜라주', description: '여러 이미지를 격자로 합쳐 한 장의 JPG 생성.', href: '/tools/image/collage', category: 'image', icon: Images, status: 'ready', phase: 2, keywords: ['collage', '콜라주', '격자', '합치기', 'image collage', '이미지 콜라주', '사진 합치기', '그리드'] },
  { id: 'image-batch-watermark', title: '일괄 워터마크', description: '여러 이미지에 동일 워터마크 일괄 적용.', href: '/tools/image/batch-watermark', category: 'image', icon: Stamp, status: 'ready', phase: 2, keywords: ['watermark', '워터마크', '일괄', 'batch', 'batch watermark', '일괄 워터마크', '여러 이미지 워터마크', '로고'] },
  { id: 'image-slideshow', title: '이미지 → 슬라이드쇼', description: '이미지 여러 장을 MP4 슬라이드쇼 영상으로.', href: '/tools/image/slideshow', category: 'image', icon: Film, status: 'ready', phase: 2, keywords: ['slideshow', '슬라이드쇼', 'mp4', '영상', 'image slideshow', '사진 영상', '이미지 동영상', '사진 슬라이드'] },
  { id: 'image-diff', title: '이미지 시각 비교', description: '두 이미지를 픽셀 비교해 차이를 빨강으로 표시.', href: '/tools/image/diff', category: 'image', icon: Diff, status: 'ready', phase: 2, keywords: ['diff', 'compare', '비교', '차이', 'image diff', '이미지 비교', '사진 비교', '픽셀 비교'] },
  { id: 'image-color-adjust', title: '이미지 색 보정', description: '밝기·대비·채도·색조·블러·세피아·반전 — 실시간.', href: '/tools/image/color-adjust', category: 'image', icon: Sliders, status: 'ready', phase: 2, keywords: ['color', 'adjust', '색', '보정', 'brightness', 'contrast'] },
  { id: 'image-denoise', title: '이미지 노이즈 제거', description: '미디언 필터로 이미지 노이즈 감소.', href: '/tools/image/denoise', category: 'image', icon: Sparkles, status: 'ready', phase: 2, keywords: ['denoise', '노이즈', 'noise', 'median', 'image denoise', '노이즈 제거', '잡음 제거', '사진 노이즈'] },
  { id: 'image-pixelate', title: '이미지 모자이크/픽셀화', description: '전체 또는 영역만 모자이크 처리.', href: '/tools/image/pixelate', category: 'image', icon: Grid3X3, status: 'ready', phase: 2, keywords: ['pixelate', 'mosaic', '모자이크', '픽셀', '픽셀화', '이미지 모자이크', '영역 가리기', 'censor'] },
  { id: 'image-exif-batch', title: 'EXIF 일괄 제거', description: '여러 사진의 GPS·촬영 정보를 한꺼번에 제거.', href: '/tools/image/exif-batch', category: 'image', icon: ShieldOff, status: 'ready', phase: 2, keywords: ['exif', 'strip', '일괄', 'privacy', '제거'] },

  // 오디오/비디오 7종
  { id: 'subtitle-edit', title: '자막 편집·시간 보정', description: 'SRT·VTT·ASS·LRC 자막 파일을 편집하고 시간을 일괄 보정하거나 포맷을 변환합니다. 영상 워크플로우의 자막 마무리에 사용합니다.', href: '/tools/text/subtitle-edit', category: 'video', icon: Subtitles, status: 'ready', phase: 7, keywords: ['subtitle', '자막', 'srt', 'vtt', 'ass', 'lrc', '편집', 'sync', '싱크', '시간보정'] },
  { id: 'subtitle-convert', title: '자막 포맷 변환', description: 'SRT ↔ VTT ↔ ASS ↔ LRC ↔ TXT 자유 변환. 영상 플랫폼별 자막 포맷 호환성 문제를 한 번에 해결합니다.', href: '/tools/text/subtitle-convert', category: 'video', icon: ArrowRightLeft, status: 'ready', phase: 7, keywords: ['subtitle', '자막', 'srt', 'vtt', 'ass', 'lrc', '변환', 'convert', '포맷'] },
  { id: 'video-burn-subtitle', title: '비디오에 자막 굽기', description: 'SRT/VTT/ASS 자막을 영상에 영구 결합.', href: '/tools/video/burn-subtitle', category: 'video', icon: Subtitles, status: 'ready', phase: 5, keywords: ['subtitle', 'burn', '자막', '굽기', '하드'] },
  { id: 'video-poster', title: '비디오 포스터 추출', description: '비디오의 특정 시각을 정지 이미지로 캡처.', href: '/tools/video/poster', category: 'video', icon: ImageIcon, status: 'ready', phase: 5, keywords: ['poster', 'thumbnail', '포스터', '썸네일', '캡처'] },
  { id: 'audio-silence-trim', title: '무음 자동 제거', description: '말 없는 구간을 자동으로 잘라내 깔끔하게.', href: '/tools/audio/silence-trim', category: 'audio', icon: VolumeX, status: 'ready', phase: 6, keywords: ['silence', '무음', 'remove', '제거', 'auto'] },
  { id: 'video-audio-replace', title: '비디오 오디오 교체', description: '영상의 오디오 트랙을 다른 음원으로 교체·믹스.', href: '/tools/video/audio-replace', category: 'video', icon: Music, status: 'ready', phase: 5, keywords: ['audio', 'replace', '교체', '믹스', 'mix', 'video'] },
  { id: 'audio-fade', title: '오디오 페이드 인/아웃', description: '오디오 시작·끝에 부드러운 페이드 효과.', href: '/tools/audio/fade', category: 'audio', icon: AudioLines, status: 'ready', phase: 6, keywords: ['fade', '페이드', 'in', 'out', 'audio fade', '페이드 인', '페이드 아웃', '음량 서서히'] },

  {
    id: 'markdown-toc',
    title: 'Markdown 목차 생성',
    description: '헤딩으로 TOC 자동 생성. 본문 삽입·번호·링크 옵션.',
    href: '/tools/docs/markdown-toc',
    category: 'docs',
    icon: ListTree,
    status: 'ready',
    phase: 7,
    keywords: ['markdown', 'toc', 'table of contents', '목차', 'md', '헤딩', 'heading'],
  },

  // ---- 2026-05-25 신규 묶음 (도구 8개) ----
  {
    id: 'age-calc',
    title: '나이 계산기',
    description: '만/연/세는 나이 동시 계산 + 마일스톤 일수.',
    href: '/tools/util/age',
    category: 'util',
    icon: CalendarClock,
    status: 'ready',
    phase: 7,
    keywords: ['나이', 'age', '만나이', '세는나이', '연나이', '생일', 'birthday'],
    addedAt: '2026-05-25',
  },
  {
    id: 'dday',
    title: 'D-day 계산기',
    description: '여러 이벤트의 D-day 를 한 화면에서 관리.',
    href: '/tools/util/dday',
    category: 'util',
    icon: Clock,
    status: 'ready',
    phase: 7,
    keywords: ['dday', '디데이', '카운트다운', 'countdown', '시험', '결혼'],
    addedAt: '2026-05-25',
  },
  {
    id: 'totp',
    title: 'TOTP 인증코드 생성기',
    description: 'Google Authenticator 호환 OTP 코드 생성.',
    href: '/tools/security/totp',
    category: 'security',
    icon: Fingerprint,
    status: 'ready',
    phase: 7,
    keywords: ['totp', 'otp', '2fa', '인증', 'authenticator', 'google', 'rfc 6238'],
    addedAt: '2026-05-25',
  },
  {
    id: 'rsa-keypair',
    title: 'RSA 키페어 생성',
    description: '브라우저에서 RSA 공개/개인 키 PEM 생성.',
    href: '/tools/security/rsa-keypair',
    category: 'security',
    icon: KeyRound,
    status: 'ready',
    phase: 7,
    keywords: ['rsa', '키페어', 'keypair', 'pem', 'public', 'private', '암호'],
    addedAt: '2026-05-25',
  },
  {
    id: 'image-ascii-art',
    title: '이미지 → ASCII 아트',
    description: '이미지를 텍스트 문자로 변환. TXT/PNG 출력.',
    href: '/tools/image/ascii-art',
    category: 'image',
    icon: Type,
    status: 'ready',
    phase: 7,
    keywords: ['ascii', '아스키', 'art', '아트', '문자', 'text', 'image'],
    addedAt: '2026-05-25',
  },
  {
    id: 'md-table',
    title: '마크다운 표 생성기',
    description: '시각 편집기로 마크다운 표 생성 · CSV 가져오기.',
    href: '/tools/dev/md-table',
    category: 'dev',
    icon: Table,
    status: 'ready',
    phase: 7,
    keywords: ['markdown', 'table', '마크다운', '표', 'md', 'github', 'notion'],
    addedAt: '2026-05-25',
  },
  {
    id: 'video-merge',
    title: '비디오 합치기',
    description: '여러 비디오를 순서대로 이어붙임. 코덱 자동 통일.',
    href: '/tools/video/merge',
    category: 'video',
    icon: Merge,
    status: 'ready',
    phase: 5,
    keywords: ['video', 'merge', 'concat', '합치기', '병합', 'mp4'],
    addedAt: '2026-05-25',
  },
  {
    id: 'video-rotate',
    title: '비디오 회전',
    description: '90/180도 회전 + 좌우/상하 반전. 픽셀 단위 변환.',
    href: '/tools/video/rotate',
    category: 'video',
    icon: RotateCw,
    status: 'ready',
    phase: 5,
    keywords: ['video', 'rotate', '회전', 'flip', '반전', '돌리기'],
    addedAt: '2026-05-25',
  },

  // ---- 2026-05-25 신규 묶음 2차 (도구 6개) ----
  {
    id: 'hwpx-viewer',
    title: 'HWPX 뷰어',
    description: '한컴 오피스 HWPX 파일을 텍스트·HTML·이미지로 추출.',
    href: '/tools/docs/hwpx-viewer',
    category: 'docs',
    icon: BookOpen,
    status: 'ready',
    phase: 5,
    keywords: ['hwpx', '한컴', 'hwp', '한글파일', '한국', 'korean', 'viewer'],
    addedAt: '2026-05-25',
  },
  {
    id: 'percentage',
    title: '퍼센트 계산기',
    description: '6가지 모드 — 백분율·증감률·할인·팁·비율.',
    href: '/tools/util/percentage',
    category: 'util',
    icon: HashIcon,
    status: 'ready',
    phase: 7,
    keywords: ['퍼센트', 'percent', '비율', '할인', '증감률', 'percentage', '계산'],
    addedAt: '2026-05-25',
  },
  {
    id: 'random-pick',
    title: '추첨기',
    description: '명단에서 무작위 추첨. Web Crypto 기반 균등 분포.',
    href: '/tools/util/random-pick',
    category: 'util',
    icon: Shuffle,
    status: 'ready',
    phase: 7,
    keywords: ['추첨', '제비뽑기', 'random', 'pick', 'draw', '뽑기'],
    addedAt: '2026-05-25',
  },
  {
    id: 'timer-stopwatch',
    title: '타이머·스톱워치',
    description: '뽀모도로 등 프리셋 + 랩 기록. 끝나면 알람.',
    href: '/tools/util/timer-stopwatch',
    category: 'util',
    icon: Clock,
    status: 'ready',
    phase: 7,
    keywords: ['타이머', 'timer', '스톱워치', 'stopwatch', '뽀모도로', 'pomodoro'],
    addedAt: '2026-05-25',
  },
  {
    id: 'url-parser',
    title: 'URL 파서',
    description: 'URL 분해/재조립 + 쿼리 파라미터 시각 편집.',
    href: '/tools/dev/url-parser',
    category: 'dev',
    icon: Link2,
    status: 'ready',
    phase: 7,
    keywords: ['url', 'parser', 'parse', 'query', '파싱', '쿼리스트링'],
    addedAt: '2026-05-25',
  },
  {
    id: 'markdown-stats',
    title: '마크다운 통계',
    description: '단어·헤딩·링크·이미지·코드 등 마크다운 구조 분석.',
    href: '/tools/text/markdown-stats',
    category: 'text',
    icon: BarChart3,
    status: 'ready',
    phase: 7,
    keywords: ['markdown', 'stats', '통계', '단어수', 'md', '읽기시간', '분석'],
    addedAt: '2026-05-25',
  },

  {
    id: 'video-blur-face',
    title: '동영상 얼굴 블러',
    description: 'AI로 영상 속 얼굴을 추적해 블러·모자이크·이모지로 가림 (오디오 유지).',
    href: '/tools/video/blur-face',
    category: 'video',
    icon: ScanFace,
    status: 'ready',
    phase: 7,
    keywords: ['동영상', '얼굴', '블러', '모자이크', 'video', 'face blur', '익명', 'privacy', '영상가림'],
    addedAt: '2026-06-01',
  },

  // ── 오피스/회사원 실무 (2026-06-01) ──────────────────────────────────────
  {
    id: 'salary-calc',
    title: '연봉 실수령액 계산기',
    description: '연봉·월급 → 4대보험·소득세 공제 후 월 실수령액.',
    href: '/tools/util/salary',
    category: 'util',
    icon: Wallet,
    status: 'ready',
    phase: 7,
    keywords: ['연봉', '실수령액', '월급', '4대보험', '소득세', 'salary', 'net pay', '급여', '세후'],
    addedAt: '2026-06-01',
  },
  {
    id: 'severance-calc',
    title: '퇴직금 계산기',
    description: '입사·퇴사일 + 평균임금 → 예상 퇴직금.',
    href: '/tools/util/severance',
    category: 'util',
    icon: Coins,
    status: 'ready',
    phase: 7,
    keywords: ['퇴직금', '평균임금', '퇴직', 'severance', '근속', '퇴사', '이직'],
    addedAt: '2026-06-01',
  },
  {
    id: 'leave-calc',
    title: '연차·주휴수당 계산기',
    description: '입사일 기준 연차 일수 + 주휴수당 산정.',
    href: '/tools/util/leave',
    category: 'util',
    icon: CalendarCheck,
    status: 'ready',
    phase: 7,
    keywords: ['연차', '주휴수당', '연차계산', '근무일', 'annual leave', '근속', '휴가'],
    addedAt: '2026-06-01',
  },
  {
    id: 'vat-calc',
    title: '부가세 계산기',
    description: '공급가액·세액·합계 어느 값에서든 역산 (10%).',
    href: '/tools/util/vat',
    category: 'util',
    icon: ReceiptText,
    status: 'ready',
    phase: 7,
    keywords: ['부가세', '부가가치세', '공급가액', '세금계산서', 'vat', '세액', '견적', '합계'],
    addedAt: '2026-06-01',
  },
  {
    id: 'seal-stamp',
    title: '직인·도장 이미지 생성기',
    description: '회사명·이름으로 원형 직인/도장 → 투명배경 PNG.',
    href: '/tools/image/seal',
    category: 'image',
    icon: Stamp,
    status: 'ready',
    phase: 7,
    keywords: ['직인', '도장', '막도장', '인감', 'seal', 'stamp', '결재', '서명', '투명배경'],
    addedAt: '2026-06-01',
  },
  {
    id: 'vcard-qr',
    title: 'vCard 명함 QR 생성기',
    description: '이름·연락처·회사 → 스캔 시 연락처 저장되는 QR.',
    href: '/tools/util/vcard-qr',
    category: 'util',
    icon: Contact,
    status: 'ready',
    phase: 7,
    keywords: ['vcard', '명함', 'qr', '연락처', 'business card', '명함qr', '전화번호'],
    addedAt: '2026-06-01',
  },
  {
    id: 'id-photo',
    title: '증명사진 규격 변환',
    description: '이력서·여권·반명함 규격으로 크롭·리사이즈 + 배경색.',
    href: '/tools/image/id-photo',
    category: 'image',
    icon: IdCard,
    status: 'ready',
    phase: 7,
    keywords: ['증명사진', '여권사진', '이력서사진', '반명함', 'id photo', 'passport photo', '규격'],
    addedAt: '2026-06-01',
  },
  {
    id: 'redact',
    title: '문서 민감정보 마스킹',
    description: '주민번호·카드·계좌·전화 자동 검출 후 가림.',
    href: '/tools/security/redact',
    category: 'security',
    icon: EyeOff,
    status: 'ready',
    phase: 7,
    keywords: ['마스킹', '민감정보', '개인정보', '주민번호', 'redaction', 'mask', '가림', '비식별'],
    addedAt: '2026-06-01',
  },
  {
    id: 'excel-formula',
    title: 'Excel 수식 생성·설명',
    description: '자연어 → 수식 생성(VLOOKUP·SUMIF 등) + 수식 해설.',
    href: '/tools/docs/excel-formula',
    category: 'docs',
    icon: Sigma,
    status: 'ready',
    phase: 7,
    keywords: ['엑셀', '수식', 'excel', 'formula', 'vlookup', 'sumif', '함수', '스프레드시트'],
    addedAt: '2026-06-01',
  },
  {
    id: 'scan-to-pdf',
    title: '스캔 → PDF',
    description: '사진으로 찍은 문서를 명암 보정 후 PDF로 묶기.',
    href: '/tools/pdf/scan',
    category: 'pdf',
    icon: ScanLine,
    status: 'ready',
    phase: 7,
    keywords: ['스캔', '문서스캐너', 'scan', 'pdf', '사진pdf', '명암보정', '서류'],
    addedAt: '2026-06-01',
  },
  {
    id: 'pdf-to-excel',
    title: 'PDF 표 → Excel',
    description: 'PDF 안 표를 인식해 xlsx·csv 로 추출.',
    href: '/tools/pdf/to-excel',
    category: 'pdf',
    icon: FileSpreadsheet,
    status: 'ready',
    phase: 7,
    keywords: ['pdf', 'excel', '표추출', 'table', 'xlsx', 'csv', '데이터', '명세서'],
    addedAt: '2026-06-01',
  },
  {
    id: 'base-converter',
    title: '진수 변환기',
    description: '2·8·10·16진수를 서로 변환하고 비트 표현을 함께 보여줍니다.',
    href: '/tools/dev/base-converter',
    category: 'dev',
    icon: Binary,
    status: 'ready',
    phase: 6,
    keywords: ['진수', 'base', 'hex', 'binary', 'octal', 'hexadecimal', '2진수', '16진수'],
    addedAt: '2026-06-07',
  },
  {
    id: 'json-to-ts',
    title: 'JSON → TypeScript',
    description: 'JSON 을 붙여넣으면 TypeScript 인터페이스를 자동 생성합니다.',
    href: '/tools/dev/json-to-ts',
    category: 'dev',
    icon: Braces,
    status: 'ready',
    phase: 6,
    keywords: ['json', 'typescript', 'interface', '타입', 'type', '변환'],
    addedAt: '2026-06-07',
  },
  {
    id: 'color-contrast',
    title: '색상 대비 검사기',
    description: '두 색의 WCAG 명도 대비비를 계산하고 AA·AAA 통과 여부를 보여줍니다.',
    href: '/tools/dev/color-contrast',
    category: 'dev',
    icon: Contrast,
    status: 'ready',
    phase: 6,
    keywords: ['대비', 'contrast', 'wcag', '접근성', 'accessibility', '명도', 'ratio'],
    addedAt: '2026-06-07',
  },
  {
    id: 'css-gradient',
    title: 'CSS 그라디언트 생성기',
    description: '색·각도를 조절해 CSS linear/radial 그라디언트를 미리보고 코드를 복사합니다.',
    href: '/tools/dev/css-gradient',
    category: 'dev',
    icon: Blend,
    status: 'ready',
    phase: 6,
    keywords: ['css', 'gradient', '그라디언트', 'linear', 'radial', 'background'],
    addedAt: '2026-06-07',
  },
  {
    id: 'html-format',
    title: 'HTML 정리·미화',
    description: 'HTML 을 들여쓰기로 정리하거나 한 줄로 압축합니다.',
    href: '/tools/dev/html-format',
    category: 'dev',
    icon: Code2,
    status: 'ready',
    phase: 6,
    keywords: ['html', 'format', 'beautify', 'prettify', '정리', '미화', 'minify'],
    addedAt: '2026-06-07',
  },
  {
    id: 'favicon-gen',
    title: '파비콘 생성기',
    description: '이미지 한 장에서 16·32·48·180·512px 파비콘과 favicon.ico 를 한 번에 만듭니다.',
    href: '/tools/image/favicon',
    category: 'image',
    icon: AppWindow,
    status: 'ready',
    phase: 6,
    keywords: ['favicon', '파비콘', 'ico', 'apple-touch-icon', '아이콘', '웹'],
    addedAt: '2026-06-07',
  },
  {
    id: 'meme-gen',
    title: '밈 생성기',
    description: '이미지에 상단·하단 텍스트를 얹어 클래식 밈을 만듭니다.',
    href: '/tools/image/meme',
    category: 'image',
    icon: Smile,
    status: 'ready',
    phase: 6,
    keywords: ['meme', '밈', 'caption', 'impact', '상단텍스트', '하단텍스트'],
    addedAt: '2026-06-07',
  },
  {
    id: 'image-flip',
    title: '이미지 반전',
    description: '이미지를 좌우 또는 상하로 뒤집어 저장합니다.',
    href: '/tools/image/flip',
    category: 'image',
    icon: FlipHorizontal2,
    status: 'ready',
    phase: 6,
    keywords: ['flip', '반전', 'mirror', '좌우', '상하', '뒤집기'],
    addedAt: '2026-06-07',
  },
  {
    id: 'image-split',
    title: '이미지 그리드 분할',
    description: '이미지를 N×M 격자로 잘라 SNS 업로드용 조각으로 저장합니다.',
    href: '/tools/image/split',
    category: 'image',
    icon: Grid2x2,
    status: 'ready',
    phase: 6,
    keywords: ['split', 'grid', '분할', '격자', '인스타그램', 'instagram', '조각'],
    addedAt: '2026-06-07',
  },
  {
    id: 'image-base64',
    title: '이미지 ↔ Base64',
    description: '이미지를 Base64 Data URI 로 변환하거나, Data URI 를 이미지로 복원합니다.',
    href: '/tools/image/base64',
    category: 'image',
    icon: FileDigit,
    status: 'ready',
    phase: 6,
    keywords: ['base64', 'data uri', '이미지', 'encode', 'decode', '인라인'],
    addedAt: '2026-06-07',
  },
  {
    id: 'image-round-corners',
    title: '모서리 둥글게',
    description: '이미지 네 모서리를 둥글게 깎아 투명 PNG 로 저장합니다.',
    href: '/tools/image/round-corners',
    category: 'image',
    icon: Squircle,
    status: 'ready',
    phase: 6,
    keywords: ['round', 'corners', '둥근모서리', 'radius', 'rounded', '투명'],
    addedAt: '2026-06-07',
  },
  {
    id: 'video-crop',
    title: '영상 자르기 (Crop)',
    description: '영상의 특정 사각형 영역만 남기고 잘라냅니다.',
    href: '/tools/video/crop',
    category: 'video',
    icon: Crop,
    status: 'ready',
    phase: 6,
    keywords: ['crop', '자르기', '영역', '트림', '화면비', 'reframe'],
    addedAt: '2026-06-07',
  },
  {
    id: 'video-speed',
    title: '영상 배속',
    description: '영상 재생 속도를 0.25×~4× 로 바꾸고 오디오 피치도 함께 조절합니다.',
    href: '/tools/video/speed',
    category: 'video',
    icon: Gauge,
    status: 'ready',
    phase: 6,
    keywords: ['speed', '배속', 'slow motion', 'fast', '느리게', '빠르게', '속도'],
    addedAt: '2026-06-07',
  },
  {
    id: 'video-mute',
    title: '영상 음소거',
    description: '영상에서 오디오 트랙을 제거해 무음 영상으로 저장합니다.',
    href: '/tools/video/mute',
    category: 'video',
    icon: VolumeX,
    status: 'ready',
    phase: 6,
    keywords: ['mute', '음소거', '무음', 'remove audio', '오디오제거', 'silent'],
    addedAt: '2026-06-07',
  },
  {
    id: 'video-watermark',
    title: '영상 워터마크',
    description: '영상 위에 로고 이미지나 텍스트 워터마크를 합성합니다.',
    href: '/tools/video/watermark',
    category: 'video',
    icon: Stamp,
    status: 'ready',
    phase: 6,
    keywords: ['watermark', '워터마크', '로고', 'logo', 'overlay', '브랜드'],
    addedAt: '2026-06-07',
  },
  {
    id: 'screen-record',
    title: '화면 녹화',
    description: '탭·창·전체 화면을 녹화해 webm 으로 저장합니다. (마이크 포함 선택)',
    href: '/tools/video/screen-record',
    category: 'video',
    icon: MonitorPlay,
    status: 'ready',
    phase: 6,
    keywords: ['screen', 'record', '화면녹화', '캡처', 'webm', '녹화'],
    addedAt: '2026-06-07',
  },
  {
    id: 'dedupe-lines',
    title: '중복 줄 제거',
    description: '여러 줄 텍스트에서 중복된 줄을 제거하고 순서를 유지합니다.',
    href: '/tools/text/dedupe-lines',
    category: 'text',
    icon: ListX,
    status: 'ready',
    phase: 6,
    keywords: ['중복', 'dedupe', 'unique', '중복제거', '줄', 'line'],
    addedAt: '2026-06-07',
  },
  {
    id: 'whitespace-clean',
    title: '공백 정리',
    description: '줄 끝 공백·중복 빈 줄·탭을 정리하고 들여쓰기를 통일합니다.',
    href: '/tools/text/whitespace',
    category: 'text',
    icon: RemoveFormatting,
    status: 'ready',
    phase: 6,
    keywords: ['공백', 'whitespace', 'trim', '빈줄', '탭', '정리', 'clean'],
    addedAt: '2026-06-07',
  },
  {
    id: 'slugify',
    title: '슬러그 변환',
    description: '제목을 URL 슬러그로 변환합니다. 한글은 로마자로 음역합니다.',
    href: '/tools/text/slugify',
    category: 'text',
    icon: Link,
    status: 'ready',
    phase: 6,
    keywords: ['slug', '슬러그', 'url', 'permalink', '음역', 'romanize', 'kebab'],
    addedAt: '2026-06-07',
  },
  {
    id: 'word-frequency',
    title: '단어 빈도 분석',
    description: '텍스트에서 단어별 출현 횟수를 세어 빈도순으로 보여줍니다.',
    href: '/tools/text/word-frequency',
    category: 'text',
    icon: ListOrdered,
    status: 'ready',
    phase: 6,
    keywords: ['빈도', 'frequency', 'word count', '단어수', '통계', '분석'],
    addedAt: '2026-06-07',
  },
  {
    id: 'column-extract',
    title: '열 추출',
    description: '구분자로 나뉜 텍스트에서 특정 열만 골라 뽑아냅니다.',
    href: '/tools/text/column-extract',
    category: 'text',
    icon: Columns3,
    status: 'ready',
    phase: 6,
    keywords: ['column', '열', '추출', '구분자', 'delimiter', 'csv', 'cut'],
    addedAt: '2026-06-07',
  },
  {
    id: 'bmi-calc',
    title: 'BMI 계산기',
    description: '키와 몸무게로 체질량지수(BMI)를 계산하고 비만도 구간을 보여줍니다.',
    href: '/tools/util/bmi',
    category: 'util',
    icon: Scale,
    status: 'ready',
    phase: 6,
    keywords: ['bmi', '체질량', '비만도', '건강', '체중', '키'],
    addedAt: '2026-06-07',
  },
  {
    id: 'loan-calc',
    title: '대출 이자 계산기',
    description: '원리금 균등상환 기준 월 상환액과 총이자를 계산합니다.',
    href: '/tools/util/loan',
    category: 'util',
    icon: Landmark,
    status: 'ready',
    phase: 6,
    keywords: ['대출', '이자', 'loan', '원리금', '상환', '금리', 'mortgage'],
    addedAt: '2026-06-07',
  },
  {
    id: 'aspect-ratio',
    title: '화면비 계산기',
    description: '가로·세로 중 하나를 바꾸면 지정한 화면비(16:9 등)로 나머지를 계산합니다.',
    href: '/tools/util/aspect-ratio',
    category: 'util',
    icon: Ratio,
    status: 'ready',
    phase: 6,
    keywords: ['화면비', 'aspect ratio', '16:9', '해상도', '비율', 'resize'],
    addedAt: '2026-06-07',
  },
  {
    id: 'pomodoro',
    title: '뽀모도로 타이머',
    description: '25분 집중 + 5분 휴식 사이클을 반복하는 생산성 타이머입니다.',
    href: '/tools/util/pomodoro',
    category: 'util',
    icon: TimerReset,
    status: 'ready',
    phase: 6,
    keywords: ['뽀모도로', 'pomodoro', '타이머', '집중', '생산성', 'focus'],
    addedAt: '2026-06-07',
  },
  {
    id: 'roman-numeral',
    title: '로마숫자 변환',
    description: '아라비아 숫자와 로마숫자(I·V·X·L·C·D·M)를 서로 변환합니다.',
    href: '/tools/util/roman-numeral',
    category: 'util',
    icon: Sigma,
    status: 'ready',
    phase: 6,
    keywords: ['로마숫자', 'roman numeral', '변환', '숫자', 'numeral'],
    addedAt: '2026-06-07',
  },
  {
    id: 'text-hash',
    title: '텍스트 해시',
    description: '입력한 텍스트의 MD5·SHA-1·SHA-256·SHA-512 해시를 생성합니다.',
    href: '/tools/security/text-hash',
    category: 'security',
    icon: Fingerprint,
    status: 'ready',
    phase: 6,
    keywords: ['hash', '해시', 'md5', 'sha256', 'sha1', 'sha512', 'checksum'],
    addedAt: '2026-06-07',
  },
  {
    id: 'password-strength',
    title: '비밀번호 강도 검사',
    description: '비밀번호의 엔트로피와 예상 크래킹 시간을 추정해 강도를 보여줍니다.',
    href: '/tools/security/password-strength',
    category: 'security',
    icon: ShieldCheck,
    status: 'ready',
    phase: 6,
    keywords: ['비밀번호', 'password', '강도', 'strength', '엔트로피', '보안'],
    addedAt: '2026-06-07',
  },
  {
    id: 'diceware',
    title: 'Diceware 패스프레이즈',
    description: '외우기 쉬운 단어 조합 패스프레이즈를 안전한 난수로 생성합니다.',
    href: '/tools/security/diceware',
    category: 'security',
    icon: Dices,
    status: 'ready',
    phase: 6,
    keywords: ['diceware', '패스프레이즈', 'passphrase', '비밀번호', '단어', 'random'],
    addedAt: '2026-06-07',
  },
  {
    id: 'jwt-encoder',
    title: 'JWT 서명 생성',
    description: '헤더·페이로드·시크릿으로 HS256 서명된 JWT 를 만듭니다.',
    href: '/tools/security/jwt-encoder',
    category: 'security',
    icon: KeySquare,
    status: 'ready',
    phase: 6,
    keywords: ['jwt', '서명', 'encode', 'hs256', 'token', '토큰'],
    addedAt: '2026-06-07',
  },
  {
    id: 'xml-format',
    title: 'XML 정리·미화',
    description: 'XML 을 들여쓰기로 정리하거나 한 줄로 압축합니다.',
    href: '/tools/docs/xml-format',
    category: 'docs',
    icon: CodeXml,
    status: 'ready',
    phase: 6,
    keywords: ['xml', 'format', 'beautify', '정리', '미화', 'minify', 'prettify'],
    addedAt: '2026-06-07',
  },
  {
    id: 'csv-viewer',
    title: 'CSV 뷰어',
    description: 'CSV 파일을 표로 미리보고 열 정렬·검색·필터를 적용합니다.',
    href: '/tools/docs/csv-viewer',
    category: 'docs',
    icon: Table,
    status: 'ready',
    phase: 6,
    keywords: ['csv', '뷰어', '표', 'table', '정렬', '검색', '미리보기'],
    addedAt: '2026-06-07',
  },
  {
    id: 'ical-gen',
    title: 'iCal 일정 생성기',
    description: '제목·시간·장소를 입력해 캘린더에 추가할 .ics 파일을 만듭니다.',
    href: '/tools/docs/ical',
    category: 'docs',
    icon: CalendarPlus,
    status: 'ready',
    phase: 6,
    keywords: ['ical', 'ics', '일정', '캘린더', 'calendar', 'event', '초대'],
    addedAt: '2026-06-07',
  },
  {
    id: 'vcard-parse',
    title: 'vCard 파서',
    description: '.vcf 연락처 파일을 읽어 이름·전화·이메일을 표로 보여주고 CSV 로 내보냅니다.',
    href: '/tools/docs/vcard-parse',
    category: 'docs',
    icon: Contact,
    status: 'ready',
    phase: 6,
    keywords: ['vcard', 'vcf', '연락처', '파서', 'contact', 'csv'],
    addedAt: '2026-06-07',
  },
  {
    id: 'audio-reverse',
    title: '오디오 거꾸로 재생',
    description: '오디오를 시간 역순으로 뒤집어 저장합니다.',
    href: '/tools/audio/reverse',
    category: 'audio',
    icon: Rewind,
    status: 'ready',
    phase: 6,
    keywords: ['reverse', '거꾸로', '역재생', 'audio', '뒤집기'],
    addedAt: '2026-06-07',
  },
  {
    id: 'audio-normalize',
    title: '오디오 음량 정규화',
    description: '오디오 음량을 일정한 기준(loudnorm)으로 맞춰 들쭉날쭉한 볼륨을 고릅니다.',
    href: '/tools/audio/normalize',
    category: 'audio',
    icon: AudioWaveform,
    status: 'ready',
    phase: 6,
    keywords: ['normalize', '정규화', '음량', 'loudness', '볼륨', 'loudnorm'],
    addedAt: '2026-06-07',
  },
  {
    id: 'tone-gen',
    title: '주파수 생성기',
    description: '지정한 주파수·파형·길이의 순음(사인·사각·삼각)을 만들어 WAV 로 저장합니다.',
    href: '/tools/audio/tone',
    category: 'audio',
    icon: Music,
    status: 'ready',
    phase: 6,
    keywords: ['tone', '주파수', 'frequency', '사인파', 'sine', 'test tone', 'hz'],
    addedAt: '2026-06-07',
  },
  {
    id: 'mic-record',
    title: '마이크 녹음기',
    description: '마이크로 음성을 녹음해 webm/ogg 오디오로 저장합니다.',
    href: '/tools/audio/record',
    category: 'audio',
    icon: Mic,
    status: 'ready',
    phase: 6,
    keywords: ['녹음', 'record', '마이크', 'voice', '음성', 'webm'],
    addedAt: '2026-06-07',
  },
];

/** status:'ready' 만 반환 */
export const readyTools = () => TOOLS.filter((t) => t.status === 'ready');

/**
 * 검색 쿼리 + 카테고리 필터 적용.
 *
 * 빈 쿼리: 카테고리만 필터하고 ready→phase 순 정렬(기존 동작 유지).
 * 비어있지 않은 쿼리: 퍼지 랭커(search.ts)로 관련도 순 정렬 —
 * 오타·어순·한글 초성("ㅇㄱㅁㅈㅇㅋ"→얼굴 모자이크)을 흡수한다.
 */
export function filterTools(query: string, category: ToolCategory | 'all'): ToolMeta[] {
  const pool =
    category === 'all' ? TOOLS : TOOLS.filter((t) => t.category === category);
  const q = query.trim();
  if (!q) {
    return [...pool].sort((a, b) => {
      if (a.status !== b.status) return a.status === 'ready' ? -1 : 1;
      return a.phase - b.phase;
    });
  }
  return searchTools(q, pool);
}
