'use client';

import { useMemo, useState } from 'react';
import { Braces, Check, Copy } from 'lucide-react';
import { Input } from '@/components/ui/input';
import { Button } from '@/components/ui/button';
import { ToolHeader } from '@/components/tools/ToolHeader';

type JsonValue = string | number | boolean | null | JsonValue[] | { [key: string]: JsonValue };

interface GenResult {
  code: string;
  error: string | null;
}

const DEFAULT_NAME = 'AutoGenerated';

/** "user_name" / "user-name" / "userName" → "UserName" (Go 내보내기용 PascalCase) */
function toGoFieldName(key: string): string {
  const parts = key.split(/[^a-zA-Z0-9]+/).filter(Boolean);
  if (parts.length === 0) return 'Field';
  const pascal = parts
    .map((part) => part.charAt(0).toUpperCase() + part.slice(1))
    .join('');
  // 숫자로 시작하면 식별자가 될 수 없으므로 접두사
  return /^[0-9]/.test(pascal) ? `Field${pascal}` : pascal;
}

function isPlainObject(value: JsonValue): value is { [key: string]: JsonValue } {
  return value !== null && typeof value === 'object' && !Array.isArray(value);
}

/** 숫자가 정수 범위면 int, 아니면 float64 */
function goNumberType(value: number): string {
  return Number.isInteger(value) ? 'int' : 'float64';
}

/** 배열 요소 타입들을 합쳐 단일 요소 타입을 결정한다(혼합이면 interface{}). */
function unifyElementTypes(types: string[]): string {
  const unique = Array.from(new Set(types));
  if (unique.length === 0) return 'interface{}';
  if (unique.length === 1) return unique[0];
  return 'interface{}';
}

/**
 * JSON 값에서 Go 타입 문자열을 만들고, 필요한 중첩 struct 정의를 structs 에 누적한다.
 * @param structs 이름→정의 본문 누적기(중복 이름 회피)
 * @param usedNames 이미 발급한 struct 이름 집합
 */
function deriveGoType(
  value: JsonValue,
  suggestedName: string,
  structs: Array<{ name: string; body: string }>,
  usedNames: Set<string>,
): string {
  if (value === null) return 'interface{}';
  if (typeof value === 'string') return 'string';
  if (typeof value === 'boolean') return 'bool';
  if (typeof value === 'number') return goNumberType(value);

  if (Array.isArray(value)) {
    if (value.length === 0) return '[]interface{}';
    const elementName = suggestedName.endsWith('s') ? suggestedName.slice(0, -1) : suggestedName;
    const elementTypes = value.map((item) =>
      deriveGoType(item, elementName || 'Item', structs, usedNames),
    );
    return `[]${unifyElementTypes(elementTypes)}`;
  }

  // 객체 → named struct
  const structName = uniqueStructName(suggestedName, usedNames);
  const fieldLines: string[] = [];
  for (const [key, fieldValue] of Object.entries(value)) {
    const fieldName = toGoFieldName(key);
    const fieldType = deriveGoType(fieldValue, fieldName, structs, usedNames);
    fieldLines.push(`\t${fieldName} ${fieldType} \`json:"${key}"\``);
  }
  structs.push({
    name: structName,
    body: `type ${structName} struct {\n${fieldLines.join('\n')}\n}`,
  });
  return structName;
}

function uniqueStructName(suggested: string, usedNames: Set<string>): string {
  const base = suggested && /[a-zA-Z]/.test(suggested) ? toGoFieldName(suggested) : 'Nested';
  let name = base;
  let counter = 2;
  while (usedNames.has(name)) {
    name = `${base}${counter}`;
    counter += 1;
  }
  usedNames.add(name);
  return name;
}

function generateGoStruct(jsonText: string, rootName: string): GenResult {
  if (!jsonText.trim()) return { code: '', error: null };

  let parsed: JsonValue;
  try {
    parsed = JSON.parse(jsonText) as JsonValue;
  } catch (err) {
    const message = err instanceof Error ? err.message : '알 수 없는 오류';
    return { code: '', error: `JSON 파싱 오류: ${message}` };
  }

  const safeRoot = rootName.trim() ? toGoFieldName(rootName.trim()) : DEFAULT_NAME;
  const usedNames = new Set<string>();
  const structs: Array<{ name: string; body: string }> = [];

  if (isPlainObject(parsed)) {
    usedNames.add(safeRoot);
    const fieldLines: string[] = [];
    for (const [key, value] of Object.entries(parsed)) {
      const fieldName = toGoFieldName(key);
      const fieldType = deriveGoType(value, fieldName, structs, usedNames);
      fieldLines.push(`\t${fieldName} ${fieldType} \`json:"${key}"\``);
    }
    structs.push({
      name: safeRoot,
      body: `type ${safeRoot} struct {\n${fieldLines.join('\n')}\n}`,
    });
  } else {
    // 최상위가 배열·원시값이면 별칭으로 표현
    usedNames.add(safeRoot);
    const goType = deriveGoType(parsed, safeRoot, structs, usedNames);
    structs.push({ name: safeRoot, body: `type ${safeRoot} ${goType}` });
  }

  // 루트(또는 별칭)를 맨 위로 정렬해 가독성 확보
  const root = structs.find((item) => item.name === safeRoot);
  const rest = structs.filter((item) => item.name !== safeRoot);
  const ordered = root ? [root, ...rest] : structs;

  return { code: ordered.map((item) => item.body).join('\n\n'), error: null };
}

export default function JsonToGoPage() {
  const [input, setInput] = useState('');
  const [name, setName] = useState('');
  const [copied, setCopied] = useState(false);

  const { code, error } = useMemo(() => generateGoStruct(input, name), [input, name]);

  async function copy() {
    if (!code) return;
    try {
      await navigator.clipboard.writeText(code);
      setCopied(true);
      window.setTimeout(() => setCopied(false), 2000);
    } catch (err) {
      console.error('clipboard write failed', err);
    }
  }

  function reset() {
    setInput('');
    setName('');
    setCopied(false);
  }

  return (
    <div className="min-h-dvh bg-background">
      <ToolHeader title="JSON → Go 구조체" onReset={reset} />
      <main className="mx-auto max-w-xl space-y-5 p-4">
        <p className="flex items-center gap-2 text-sm text-muted-foreground">
          <Braces className="h-4 w-4 text-primary" aria-hidden />
          JSON 을 Go struct 타입 정의로 변환합니다.
        </p>

        <label className="block space-y-1">
          <span className="text-sm font-medium">최상위 구조체 이름</span>
          <Input value={name} onChange={(event) => setName(event.target.value)} placeholder={DEFAULT_NAME} />
        </label>

        <label className="block space-y-1">
          <span className="text-sm font-medium">JSON 입력</span>
          <textarea
            className="min-h-48 w-full rounded-xl border bg-card p-3 font-mono text-sm"
            value={input}
            onChange={(event) => setInput(event.target.value)}
            placeholder={'{\n  "id": 1,\n  "name": "kim",\n  "tags": ["a", "b"]\n}'}
            aria-label="JSON 입력"
          />
        </label>

        {error && (
          <div role="alert" className="rounded-md border border-destructive/50 bg-destructive/10 p-3 text-sm text-destructive">
            {error}
          </div>
        )}

        {code && (
          <div className="space-y-2">
            <div className="flex items-center justify-between">
              <span className="text-sm font-medium">결과</span>
              <Button variant="outline" size="sm" onClick={copy} aria-label="결과 복사">
                {copied ? <Check className="h-3.5 w-3.5" /> : <Copy className="h-3.5 w-3.5" />}
                {copied ? '복사됨' : '복사'}
              </Button>
            </div>
            <pre className="overflow-x-auto rounded-xl border bg-muted/40 p-3 font-mono text-sm">
              <code>{code}</code>
            </pre>
          </div>
        )}
      </main>
    </div>
  );
}
